import 'dart:io';

import 'package:flutter/services.dart' show FontLoader, rootBundle;
import 'package:flutter_test/flutter_test.dart';
import 'package:proframe/app/export/elevation_painter.dart';
import 'package:proframe/domain/design_document.dart';
import 'package:proframe/domain/geometry/point2.dart';
import 'package:proframe/domain/geometry/polygon.dart';
import 'package:proframe/domain/measurement.dart';
import 'package:proframe/domain/panel.dart';
import 'package:proframe/domain/panel_divider.dart';
import 'package:proframe/domain/panel_note.dart';
import 'package:proframe/domain/product/finish.dart';
import 'package:proframe/domain/product/opening.dart';
import 'package:proframe/domain/product/product_basics.dart';
import 'package:proframe/domain/sketch.dart';
import 'package:proframe/infrastructure/export/pdf_design_sheet.dart';
import 'package:proframe/infrastructure/export/project_file.dart';

/// Writes the sample project and its exports into `samples/`.
///
/// Generated by the real export path rather than hand-made, so what ships as a
/// sample is exactly what the app produces (spec section 15).
///
/// Run with: `flutter test test/samples_generator_test.dart`
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  final design = _sampleDesign();

  setUpAll(() async {
    // `flutter test` ships no real fonts, so text would rasterise as boxes and
    // the sample PNG would misrepresent what the app actually draws. Loading
    // the app's own bundled faces makes the sample the real thing.
    await (FontLoader('Noto Sans')
          ..addFont(rootBundle.load('assets/fonts/NotoSans-Regular.ttf'))
          ..addFont(rootBundle.load('assets/fonts/NotoSans-Bold.ttf')))
        .load();
    await (FontLoader('Noto Sans Arabic')
          ..addFont(rootBundle.load('assets/fonts/NotoSansArabic-Regular.ttf')))
        .load();
  });

  test('writes the sample project file', () async {
    final file = File('samples/kitchen-window.proframe');
    await file.writeAsString(ProjectFile.encode(design));

    // It must reopen, or it is not a sample of anything.
    final reopened = ProjectFile.decode(await file.readAsString());
    expect(reopened.panels, hasLength(3));
    expect(reopened.allNotes, hasLength(4));
  });

  test('writes the sample PDF design sheet', () async {
    final bytes = await PdfDesignSheet.build(design);
    await File('samples/kitchen-window.pdf').writeAsBytes(bytes);

    expect(String.fromCharCodes(bytes.take(4)), '%PDF');
  });

  testWidgets('writes the sample PNG drawing', (tester) async {
    // Everything here runs inside `runAsync`: `Picture.toImage` and file I/O
    // are both real asynchronous work, and the fake-async zone a widget test
    // runs in never completes either of them.
    final sizes = await tester.runAsync(() async {
      final withDimensions = await renderElevationPng(design);
      final plain = await renderElevationPng(
        design,
        options: const ElevationOptions(
          showDimensions: false,
          showNotes: false,
        ),
      );

      await File('samples/kitchen-window.png').writeAsBytes(withDimensions);
      await File('samples/kitchen-window-plain.png').writeAsBytes(plain);

      return (
        header: withDimensions.take(4).toList(),
        full: withDimensions.length,
        plain: plain.length,
      );
    });

    expect(sizes!.header, [0x89, 0x50, 0x4E, 0x47]);
    // Hiding the dimensions really does produce a different drawing.
    expect(sizes.plain, isNot(sizes.full));
  });

  test('writes a readable summary beside them', () async {
    final buffer = StringBuffer()
      ..writeln('# Sample: ${design.name}')
      ..writeln()
      ..writeln('Generated by ProFrame\'s own export path.')
      ..writeln()
      ..writeln('| Field | Value |')
      ..writeln('| --- | --- |')
      ..writeln('| Product | ${design.category.label} |')
      ..writeln('| Material | ${design.material.label} |')
      ..writeln('| Colour | ${design.finish.name} |')
      ..writeln('| Profile | ${design.profileSystem.name} |')
      ..writeln(
        '| Overall | ${design.overallWidth!.millimetres.round()} × '
        '${design.overallHeight!.millimetres.round()} mm |',
      )
      ..writeln('| Measured as | ${design.dimensionReference.label} |')
      ..writeln('| Viewed from | ${design.viewedFrom.label} |')
      ..writeln('| Panels | ${design.panels.length} '
          '(${design.fixedPanelCount} CH, ${design.openingPanelCount} Z) |')
      ..writeln()
      ..writeln('## Notes')
      ..writeln();
    for (final note in design.allNotes) {
      buffer.writeln('- **${note.source}** — ${note.text}');
    }
    buffer
      ..writeln()
      ..writeln('## Files')
      ..writeln()
      ..writeln('| File | What it is |')
      ..writeln('| --- | --- |')
      ..writeln('| `kitchen-window.proframe` | The editable project. '
          'The only one that reopens for editing. |')
      ..writeln('| `kitchen-window.pdf` | The design sheet. |')
      ..writeln('| `kitchen-window.png` | The drawing, with dimensions and '
          'note markers. |')
      ..writeln('| `kitchen-window-plain.png` | The same drawing without '
          'them. |');

    await File('samples/README.md').writeAsString(buffer.toString());
    expect(File('samples/README.md').existsSync(), isTrue);
  });
}

/// A three-panel PVC window with notes on two of its panels.
DesignDocument _sampleDesign() {
  final outline = Polygon.rectangle(width: 1800, height: 1400);
  return DesignDocument.blank(
    id: 'sample-kitchen-window',
    category: ProductCategory.window,
    material: FrameMaterial.pvc,
    name: 'Kitchen window',
    now: DateTime.utc(2026, 9, 12, 9),
  ).copyWith(
    outline: outline,
    finish: StockFinishes.anthracite,
    overallWidth: const Measurement.confirmed(1800),
    overallHeight: const Measurement.confirmed(1400),
    designNote: 'Customer asked for obscure glass in the opening leaf. '
        'Delivery to the side entrance, not the front.',
    dividers: const [
      PanelDivider(
        id: 'v1',
        start: Point2(600, 0),
        end: Point2(600, 1400),
        spansFullFrame: true,
      ),
      PanelDivider(
        id: 'v2',
        start: Point2(1200, 0),
        end: Point2(1200, 1400),
        spansFullFrame: true,
      ),
    ],
    panels: [
      Panel.fixed(
        id: 'left',
        boundary: Polygon.rectangle(width: 600, height: 1400),
        notes: const [
          PanelNote(id: 'n1', text: 'توري', position: Point2(0.5, 0.25)),
        ],
      ).copyWith(hasMesh: true),
      Panel.opening(
        id: 'middle',
        boundary: Polygon.rectangle(
          width: 600,
          height: 1400,
          topLeft: const Point2(600, 0),
        ),
        opening: const OpeningSpec(
          hingeSide: HingeSide.left,
          direction: OpeningDirection.inward,
          isConfirmed: true,
        ),
        notes: const [
          PanelNote(id: 'n2', text: 'Obscure glass', position: Point2(0.5, 0.3)),
          PanelNote(
            id: 'n3',
            text: 'Restrictor fitted',
            position: Point2(0.5, 0.7),
          ),
        ],
      ),
      Panel.fixed(
        id: 'right',
        boundary: Polygon.rectangle(
          width: 600,
          height: 1400,
          topLeft: const Point2(1200, 0),
        ),
      ),
    ],
    sketch: const Sketch(
      strokes: [
        Stroke(
          id: 'ink1',
          points: [
            Point2(0, 0),
            Point2(1800, 6),
            Point2(1796, 1400),
            Point2(4, 1398),
            Point2(0, 0),
          ],
        ),
      ],
    ),
  );
}
