import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

// ---------------------------------------------------------------------------
// `lib/` holds what the architecture in CLAUDE.md says it holds, and nothing
// else.
//
// This guards the working copy rather than any one function, and it exists
// because of a real morning lost to it. The application used to have a
// localisation layer under `lib/core/localization/`, part of it written by
// hand and part of it **generated** by `flutter gen-l10n`. Rebuilding the
// application took the layer out — but git only removes what git tracks, and
// generated files were never tracked. They stayed on disk, in a folder
// nothing references, referring to packages the pubspec no longer has, and
// the editor reported a dozen errors in a project whose own `flutter
// analyze` was clean. There is nothing to find in the code, because the
// fault is not in the code: it is a folder that should not be there.
//
// So `flutter test` says so plainly, with the path and what to do about it.
// ---------------------------------------------------------------------------

/// The layers, exactly as the architecture names them.
const layers = {'app', 'domain', 'infrastructure'};

/// The one file that is allowed to sit above them.
const entryPoint = 'main.dart';

void main() {
  test('lib/ holds the three layers and main.dart, and nothing else', () {
    final lib = Directory('lib');
    expect(lib.existsSync(), isTrue);

    final strays = <String>[];
    for (final entry in lib.listSync()) {
      final name = entry.uri.pathSegments
          .where((part) => part.isNotEmpty)
          .last;
      if (entry is Directory && layers.contains(name)) continue;
      if (entry is File && name == entryPoint) continue;
      strays.add(entry.path);
    }

    expect(
      strays,
      isEmpty,
      reason: 'Something is in lib/ that the architecture does not name:\n'
          '  ${strays.join('\n  ')}\n\n'
          'If you did not put it there, it is left over from an earlier '
          'version of the application — most likely generated files that '
          'git never tracked, so removing the layer never removed them. '
          'Delete it: they are built from nothing that is still here, and '
          'the editor will report errors in them for as long as they exist.\n\n'
          'lib/ holds app/, domain/, infrastructure/ and main.dart.',
    );
  });

  test('nothing generated by a translation tool is left in the tree', () {
    // The specific shape of the one that was: `flutter gen-l10n` output, and
    // the .arb files it reads. The application does not use either, and a
    // file of this name can only be left over.
    final left = <String>[];
    for (final entry in Directory('lib').listSync(recursive: true)) {
      if (entry is! File) continue;
      final name = entry.uri.pathSegments.last;
      if (name.startsWith('app_localizations') || name.endsWith('.arb')) {
        left.add(entry.path);
      }
    }

    expect(left, isEmpty,
        reason: 'Generated translation files are still on disk:\n'
            '  ${left.join('\n  ')}\n\n'
            'Nothing in the application reads them and the pubspec declares '
            'no localisation. Delete them.');
  });
}
