import 'package:uuid/uuid.dart';

/// Central id / document-number generation.
///
/// Entity ids are UUIDv4 (stable, offline-safe, collision-free without a
/// server round-trip — required for the offline-first configurator).
/// Human-facing document numbers (quotations/orders/projects) use a
/// sequential, year-scoped format configured in [Settings] and are
/// generated by [DocumentNumberSequence] instead of this class.
class IdGenerator {
  IdGenerator._();

  static const Uuid _uuid = Uuid();

  static String generate() => _uuid.v4();
}

/// Generates human-facing sequential document numbers such as
/// `Q-2026-000001`, `ORD-2026-000001`, `PRJ-2026-000001`.
///
/// The prefix and padding are configurable per [Settings] so every factory
/// can adopt its own numbering scheme without touching source code.
class DocumentNumberSequence {
  final String prefix;
  final int padding;

  const DocumentNumberSequence({required this.prefix, this.padding = 6});

  String format({required int year, required int sequence}) {
    final paddedSequence = sequence.toString().padLeft(padding, '0');
    return '$prefix-$year-$paddedSequence';
  }
}
