// Writes the domain's words from the application's English ARB file.
//
//     dart run tool/generate_domain_words.dart
//
// The domain is pure Dart, so it cannot read the generated
// `AppLocalizations`. What it says to the user — a requirement before a
// price, a payment the ledger refuses, a part named in a problem — it says
// through `Words` (lib/domain/text/words.dart), one method a message. This
// script makes that interface, its English (`EnglishWords`, which every
// domain test reads) and the application's adapter (`ArbWords`, which hands
// each method to the generated localizations) from the ARB entries whose
// description starts with `[domain]`. So a word is written once, in
// lib/app/l10n/app_en.arb, and translated once, in app_ckb.arb.
//
// Run it after `[domain]` entries are added or changed, then
// `flutter gen-l10n`. `test/app/the_words_are_one_set_test.dart` fails
// when the files written here are behind the ARB.

import 'dart:convert';
import 'dart:io';

const arbPath = 'lib/app/l10n/app_en.arb';
const domainPath = 'lib/domain/text/words.dart';
const adapterPath = 'lib/app/l10n/arb_words.dart';

void main() {
  final outputs = generate(File(arbPath).readAsStringSync());
  File(domainPath).writeAsStringSync(outputs.domain);
  File(adapterPath).writeAsStringSync(outputs.adapter);
  stdout.writeln('Wrote $domainPath and $adapterPath.');
}

/// One message the domain says.
class DomainWord {
  final String key;
  final String template;
  final String description;

  /// Each placeholder's name and Dart type, in the order they appear.
  final List<(String, String)> parameters;

  const DomainWord(this.key, this.template, this.description, this.parameters);
}

/// The domain's messages in [arb], in the order the file has them.
List<DomainWord> domainWordsIn(String arb) {
  final entries = jsonDecode(arb) as Map<String, Object?>;
  final words = <DomainWord>[];
  for (final MapEntry(:key, :value) in entries.entries) {
    if (key.startsWith('@')) continue;
    final meta = entries['@$key'];
    if (meta is! Map<String, Object?>) continue;
    final description = meta['description'];
    if (description is! String || !description.startsWith('[domain]')) {
      continue;
    }
    final template = value! as String;
    if (RegExp(r',\s*(plural|select)\s*,').hasMatch(template)) {
      throw FormatException(
        '$key: the domain says no plural or select; '
        'it chooses between two messages itself.',
      );
    }
    final declared = meta['placeholders'];
    final types = <String, String>{
      if (declared is Map<String, Object?>)
        for (final MapEntry(:key, :value) in declared.entries)
          key: switch ((value as Map<String, Object?>?)?['type']) {
            'int' => 'int',
            _ => 'String',
          },
    };
    final ordered = <(String, String)>[];
    for (final m in RegExp(r'\{(\w+)\}').allMatches(template)) {
      final name = m.group(1)!;
      if (ordered.any((p) => p.$1 == name)) continue;
      ordered.add((name, types[name] ?? 'String'));
    }
    for (final name in types.keys) {
      if (!ordered.any((p) => p.$1 == name)) {
        throw FormatException('$key: placeholder {$name} is not used.');
      }
    }
    words.add(
      DomainWord(
        key,
        template,
        description.substring('[domain]'.length).trim(),
        ordered,
      ),
    );
  }
  return words;
}

String _signature(DomainWord w) => w.parameters.isEmpty
    ? 'get ${w.key}'
    : '${w.key}(${w.parameters.map((p) => '${p.$2} ${p.$1}').join(', ')})';

/// [template] as a Dart single-quoted string with its placeholders
/// interpolated.
String _dartString(DomainWord w) {
  final out = StringBuffer("'");
  var i = 0;
  final t = w.template;
  while (i < t.length) {
    final c = t[i];
    if (c == '{') {
      final end = t.indexOf('}', i);
      final name = t.substring(i + 1, end);
      final next = end + 1 < t.length ? t[end + 1] : '';
      final bare = !RegExp(r'[A-Za-z0-9_]').hasMatch(next);
      out.write(bare ? '\$$name' : '\${$name}');
      i = end + 1;
      continue;
    }
    out.write(switch (c) {
      r'\' => r'\\',
      "'" => r"\'",
      r'$' => r'\$',
      '\n' => r'\n',
      _ => c,
    });
    i++;
  }
  out.write("'");
  return out.toString();
}

({String domain, String adapter}) generate(String arb) {
  final words = domainWordsIn(arb);
  const header =
      '// Generated by tool/generate_domain_words.dart from '
      'lib/app/l10n/app_en.arb.\n'
      '// Do not edit: change the ARB entry and run the tool again.\n'
      '// dart format off\n';

  final domain = StringBuffer(header)
    ..writeln()
    ..writeln('/// What the domain says to the user, one method a message.')
    ..writeln('///')
    ..writeln('/// The domain composes its sentences through these, so the')
    ..writeln('/// application can have them in whichever language is shown;')
    ..writeln('/// [EnglishWords] is the English, which is also what every')
    ..writeln('/// domain object says when nobody asks for another language.')
    ..writeln('abstract interface class Words {');
  for (final w in words) {
    domain
      ..writeln('  /// ${w.description}')
      ..writeln('  String ${_signature(w)};')
      ..writeln();
  }
  domain
    ..writeln('}')
    ..writeln()
    ..writeln('/// The domain in English.')
    ..writeln('class EnglishWords implements Words {')
    ..writeln('  const EnglishWords();')
    ..writeln();
  for (final w in words) {
    domain
      ..writeln('  @override')
      ..writeln('  String ${_signature(w)} =>')
      ..writeln('      ${_dartString(w)};')
      ..writeln();
  }
  domain.writeln('}');

  final adapter = StringBuffer(header)
    ..writeln()
    ..writeln("import '../../domain/text/words.dart';")
    ..writeln("import 'app_localizations.dart';")
    ..writeln()
    ..writeln("/// The domain's words, in the language [l] is in.")
    ..writeln('class ArbWords implements Words {')
    ..writeln('  final AppLocalizations l;')
    ..writeln()
    ..writeln('  const ArbWords(this.l);')
    ..writeln()
    ..writeln(
      '  // Two are the same words when they are the same language, so a',
    )
    ..writeln(
      '  // painter handed a fresh one each build does not repaint for it.',
    )
    ..writeln('  @override')
    ..writeln('  bool operator ==(Object other) =>')
    ..writeln('      other is ArbWords && other.l.localeName == l.localeName;')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  int get hashCode => l.localeName.hashCode;')
    ..writeln();
  for (final w in words) {
    final call = w.parameters.isEmpty
        ? 'l.${w.key}'
        : 'l.${w.key}(${w.parameters.map((p) => p.$1).join(', ')})';
    adapter
      ..writeln('  @override')
      ..writeln('  String ${_signature(w)} => $call;')
      ..writeln();
  }
  adapter.writeln('}');
  return (domain: domain.toString(), adapter: adapter.toString());
}
