// Generated by tool/generate_domain_words.dart from lib/app/l10n/app_en.arb.
// Do not edit: change the ARB entry and run the tool again.
// dart format off

import '../../domain/text/words.dart';
import 'app_localizations.dart';

/// The domain's words, in the language [l] is in.
class ArbWords implements Words {
  final AppLocalizations l;

  const ArbWords(this.l);

  // Two are the same words when they are the same language, so a
  // painter handed a fresh one each build does not repaint for it.
  @override
  bool operator ==(Object other) =>
      other is ArbWords && other.l.localeName == l.localeName;

  @override
  int get hashCode => l.localeName.hashCode;

  @override
  String get kindDoor => l.kindDoor;

  @override
  String get kindWindow => l.kindWindow;

  @override
  String get kindBoth => l.kindBoth;

  @override
  String get kindSliding => l.kindSliding;

  @override
  String get kindAngled => l.kindAngled;

  @override
  String get kindUnsupported => l.kindUnsupported;

  @override
  String get nounDoor => l.nounDoor;

  @override
  String get nounWindow => l.nounWindow;

  @override
  String get nounBoth => l.nounBoth;

  @override
  String get nounSliding => l.nounSliding;

  @override
  String get nounAngled => l.nounAngled;

  @override
  String get nounUnsupported => l.nounUnsupported;

  @override
  String untitledDesign(String noun) => l.untitledDesign(noun);

  @override
  String get constructionPending => l.constructionPending;

  @override
  String get constructionPanel => l.constructionPanel;

  @override
  String get constructionGlass => l.constructionGlass;

  @override
  String get constructionBoth => l.constructionBoth;

  @override
  String get matUpvc => l.matUpvc;

  @override
  String get matAluminium => l.matAluminium;

  @override
  String get matWood => l.matWood;

  @override
  String get matSteel => l.matSteel;

  @override
  String get matClearGlass => l.matClearGlass;

  @override
  String get matFrostedGlass => l.matFrostedGlass;

  @override
  String get matTintedGlass => l.matTintedGlass;

  @override
  String get matPanel => l.matPanel;

  @override
  String get matLouvre => l.matLouvre;

  @override
  String get matMesh => l.matMesh;

  @override
  String get matRubber => l.matRubber;

  @override
  String get classGlass => l.classGlass;

  @override
  String get classPanel => l.classPanel;

  @override
  String get classPvc => l.classPvc;

  @override
  String get classAluminium => l.classAluminium;

  @override
  String get classWood => l.classWood;

  @override
  String get classRubber => l.classRubber;

  @override
  String get classMetal => l.classMetal;

  @override
  String get classHandleMetal => l.classHandleMetal;

  @override
  String get classHingeMetal => l.classHingeMetal;

  @override
  String get classMesh => l.classMesh;

  @override
  String get colourBlack => l.colourBlack;

  @override
  String get colourWhite => l.colourWhite;

  @override
  String get colourSilver => l.colourSilver;

  @override
  String get colourGrey => l.colourGrey;

  @override
  String get colourBronze => l.colourBronze;

  @override
  String get colourBrown => l.colourBrown;

  @override
  String get colourOffWhite => l.colourOffWhite;

  @override
  String get colourCream => l.colourCream;

  @override
  String get colourGraphite => l.colourGraphite;

  @override
  String get colourDeepGreen => l.colourDeepGreen;

  @override
  String get colourSteelBlue => l.colourSteelBlue;

  @override
  String get colourOak => l.colourOak;

  @override
  String get colourWalnut => l.colourWalnut;

  @override
  String get colourOxblood => l.colourOxblood;

  @override
  String get colourClearGlass => l.colourClearGlass;

  @override
  String get colourFrosted => l.colourFrosted;

  @override
  String get colourWarmCream => l.colourWarmCream;

  @override
  String get glassClear => l.glassClear;

  @override
  String get glassTinted => l.glassTinted;

  @override
  String get glassFrosted => l.glassFrosted;

  @override
  String get glassDark => l.glassDark;

  @override
  String get glassBlueGrey => l.glassBlueGrey;

  @override
  String get mechFixed => l.mechFixed;

  @override
  String get mechFixedHint => l.mechFixedHint;

  @override
  String get mechHingedLeft => l.mechHingedLeft;

  @override
  String get mechHingedLeftHint => l.mechHingedLeftHint;

  @override
  String get mechHingedRight => l.mechHingedRight;

  @override
  String get mechHingedRightHint => l.mechHingedRightHint;

  @override
  String get mechTopHung => l.mechTopHung;

  @override
  String get mechTopHungHint => l.mechTopHungHint;

  @override
  String get mechBottomHung => l.mechBottomHung;

  @override
  String get mechBottomHungHint => l.mechBottomHungHint;

  @override
  String get mechSlidingLeft => l.mechSlidingLeft;

  @override
  String get mechSlidingLeftHint => l.mechSlidingLeftHint;

  @override
  String get mechSlidingRight => l.mechSlidingRight;

  @override
  String get mechSlidingRightHint => l.mechSlidingRightHint;

  @override
  String get mechTiltAndTurn => l.mechTiltAndTurn;

  @override
  String get mechTiltAndTurnHint => l.mechTiltAndTurnHint;

  @override
  String get mechBifold => l.mechBifold;

  @override
  String get mechBifoldHint => l.mechBifoldHint;

  @override
  String get mechPivot => l.mechPivot;

  @override
  String get mechPivotHint => l.mechPivotHint;

  @override
  String get hwHandle => l.hwHandle;

  @override
  String get hwLever => l.hwLever;

  @override
  String get hwKnob => l.hwKnob;

  @override
  String get hwLock => l.hwLock;

  @override
  String get hwHinge => l.hwHinge;

  @override
  String get hwLetterplate => l.hwLetterplate;

  @override
  String get hwPeephole => l.hwPeephole;

  @override
  String get hwCloser => l.hwCloser;

  @override
  String get hwPull => l.hwPull;

  @override
  String get hwScreen => l.hwScreen;

  @override
  String get hwSensor => l.hwSensor;

  @override
  String get elFrame => l.elFrame;

  @override
  String get elSection => l.elSection;

  @override
  String get elNote => l.elNote;

  @override
  String get elArrow => l.elArrow;

  @override
  String get elVerticalDivider => l.elVerticalDivider;

  @override
  String get elHorizontalDivider => l.elHorizontalDivider;

  @override
  String get elAngledDivider => l.elAngledDivider;

  @override
  String get payTypePayment => l.payTypePayment;

  @override
  String get payTypeRefund => l.payTypeRefund;

  @override
  String get payCash => l.payCash;

  @override
  String get payBankTransfer => l.payBankTransfer;

  @override
  String get payCard => l.payCard;

  @override
  String get payOther => l.payOther;

  @override
  String get payLegacy => l.payLegacy;

  @override
  String payOtherDetail(String detail) => l.payOtherDetail(detail);

  @override
  String get discountPercent => l.discountPercent;

  @override
  String get discountFixed => l.discountFixed;

  @override
  String get projectionPerspective => l.projectionPerspective;

  @override
  String get projectionParallel => l.projectionParallel;

  @override
  String get groupNormalProfile => l.groupNormalProfile;

  @override
  String get groupOpeningProfile => l.groupOpeningProfile;

  @override
  String get groupOtherProfile => l.groupOtherProfile;

  @override
  String get groupColour => l.groupColour;

  @override
  String get groupGlass => l.groupGlass;

  @override
  String get groupPanel => l.groupPanel;

  @override
  String get groupHardware => l.groupHardware;

  @override
  String get groupLabour => l.groupLabour;

  @override
  String get groupInstallation => l.groupInstallation;

  @override
  String get unitEach => l.unitEach;

  @override
  String get glassNotIncluded => l.glassNotIncluded;

  @override
  String get glassNothingToCharge => l.glassNothingToCharge;

  @override
  String get glassNotUsed => l.glassNotUsed;

  @override
  String get catSystemAluminium => l.catSystemAluminium;

  @override
  String get catBendShoulderAluminium => l.catBendShoulderAluminium;

  @override
  String get partBorder => l.partBorder;

  @override
  String get partLines => l.partLines;

  @override
  String openingNumbered(int number) => l.openingNumbered(number);

  @override
  String get openingAlone => l.openingAlone;

  @override
  String get openingThe => l.openingThe;

  @override
  String get partA => l.partA;

  @override
  String get placeHead => l.placeHead;

  @override
  String get placeSill => l.placeSill;

  @override
  String get placeLeftJamb => l.placeLeftJamb;

  @override
  String get placeRightJamb => l.placeRightJamb;

  @override
  String get placeRakingUpperLeft => l.placeRakingUpperLeft;

  @override
  String get placeRakingUpperRight => l.placeRakingUpperRight;

  @override
  String get placeRakingLowerLeft => l.placeRakingLowerLeft;

  @override
  String get placeRakingLowerRight => l.placeRakingLowerRight;

  @override
  String lineNumbered(int n) => l.lineNumbered(n);

  @override
  String lineInside(int n, String opening) => l.lineInside(n, opening);

  @override
  String get measFrameBorder => l.measFrameBorder;

  @override
  String get measBarThickness => l.measBarThickness;

  @override
  String get measOverallWidth => l.measOverallWidth;

  @override
  String get measOverallHeight => l.measOverallHeight;

  @override
  String get axisWidth => l.axisWidth;

  @override
  String get axisHeight => l.axisHeight;

  @override
  String measFixedLight(int n) => l.measFixedLight(n);

  @override
  String measPane(String around, String material, int n) => l.measPane(around, material, n);

  @override
  String sideHeight(String side) => l.sideHeight(side);

  @override
  String sideWidth(String side) => l.sideWidth(side);

  @override
  String joinAnd(String a, String b) => l.joinAnd(a, b);

  @override
  String joinOr(String a, String b) => l.joinOr(a, b);

  @override
  String get reqUnsupported => l.reqUnsupported;

  @override
  String get reqNotRead => l.reqNotRead;

  @override
  String get reqFrame => l.reqFrame;

  @override
  String get reqDraw => l.reqDraw;

  @override
  String reqGeometry(String problem) => l.reqGeometry(problem);

  @override
  String get reqConstruction => l.reqConstruction;

  @override
  String get reqPanelOrGlass => l.reqPanelOrGlass;

  @override
  String reqOpeningKind(String opening) => l.reqOpeningKind(opening);

  @override
  String reqFrameSizes(String which) => l.reqFrameSizes(which);

  @override
  String reqGroupSizes(String group, String which) => l.reqGroupSizes(group, which);

  @override
  String get reqProfile => l.reqProfile;

  @override
  String reqCategoryAll(String material, String choices) => l.reqCategoryAll(material, choices);

  @override
  String reqCategorySome(String choices, String parts) => l.reqCategorySome(choices, parts);

  @override
  String readinessMoreOne(String first, int more) => l.readinessMoreOne(first, more);

  @override
  String readinessMoreMany(String first, int more) => l.readinessMoreMany(first, more);

  @override
  String get takeoffNothing => l.takeoffNothing;

  @override
  String get takeoffOutline => l.takeoffOutline;

  @override
  String get takeoffNoSize => l.takeoffNoSize;

  @override
  String colourNotForMaterial(String material) => l.colourNotForMaterial(material);

  @override
  String colourNotConfigured(String material) => l.colourNotConfigured(material);

  @override
  String get colourUnavailable => l.colourUnavailable;

  @override
  String colourNoProfile(String material) => l.colourNoProfile(material);

  @override
  String get gradeStandard => l.gradeStandard;

  @override
  String get gradeNonStandard => l.gradeNonStandard;

  @override
  String get gradeSpecial => l.gradeSpecial;

  @override
  String get engineUnsupported => l.engineUnsupported;

  @override
  String engineNoCategory(String kind) => l.engineNoCategory(kind);

  @override
  String engineMissing(String what) => l.engineMissing(what);

  @override
  String engineExtraCurrency(String name, String currency, String listCurrency) => l.engineExtraCurrency(name, currency, listCurrency);

  @override
  String missProfile(String material) => l.missProfile(material);

  @override
  String missBorderLines(String what) => l.missBorderLines(what);

  @override
  String missInfill(String material) => l.missInfill(material);

  @override
  String missPiece(String piece) => l.missPiece(piece);

  @override
  String get custom => l.custom;

  @override
  String get notSelected => l.notSelected;

  @override
  String lineProfile(String what, String part) => l.lineProfile(what, part);

  @override
  String lineOpeningProfile(String material) => l.lineOpeningProfile(material);

  @override
  String lineColour(String colour, String material, String grade) => l.lineColour(colour, material, grade);

  @override
  String get lineTrack => l.lineTrack;

  @override
  String lineGlass(String look) => l.lineGlass(look);

  @override
  String lineSealed(String glass) => l.lineSealed(glass);

  @override
  String linePanel(String colour) => l.linePanel(colour);

  @override
  String linePieces(String piece) => l.linePieces(piece);

  @override
  String get lineRollers => l.lineRollers;

  @override
  String get lineMaking => l.lineMaking;

  @override
  String get lineMakingArea => l.lineMakingArea;

  @override
  String get lineMakingMaterials => l.lineMakingMaterials;

  @override
  String get lineInstallation => l.lineInstallation;

  @override
  String get lineInstallationArea => l.lineInstallationArea;

  @override
  String get stateNotRead => l.stateNotRead;

  @override
  String get stateComplete => l.stateComplete;

  @override
  String get stateIncomplete => l.stateIncomplete;

  @override
  String get noteNotRead => l.noteNotRead;

  @override
  String get noteNotCalculated => l.noteNotCalculated;

  @override
  String get noteRecalculate => l.noteRecalculate;

  @override
  String get noteIncomplete => l.noteIncomplete;

  @override
  String get noteUnavailable => l.noteUnavailable;

  @override
  String get msgRecalculate => l.msgRecalculate;

  @override
  String get msgCalculate => l.msgCalculate;

  @override
  String get reasonUnsupported => l.reasonUnsupported;

  @override
  String get reasonListCannot => l.reasonListCannot;

  @override
  String get gfPartOfDesign => l.gfPartOfDesign;

  @override
  String get gfFrame => l.gfFrame;

  @override
  String gfMemberOfFrame(String member) => l.gfMemberOfFrame(member);

  @override
  String gfLineInside(String parent) => l.gfLineInside(parent);

  @override
  String get gfBar => l.gfBar;

  @override
  String get gfMullion => l.gfMullion;

  @override
  String get gfTransom => l.gfTransom;

  @override
  String get gfSlopedBar => l.gfSlopedBar;

  @override
  String gfPaneOf(String parent) => l.gfPaneOf(parent);

  @override
  String gfRegionOf(String opening) => l.gfRegionOf(opening);

  @override
  String get gfFixedLight => l.gfFixedLight;

  @override
  String gfPieceOf(String piece, String opening) => l.gfPieceOf(piece, opening);

  @override
  String gfPiece(String piece) => l.gfPiece(piece);

  @override
  String gfDimensionGiven(String size) => l.gfDimensionGiven(size);

  @override
  String get gfDimension => l.gfDimension;

  @override
  String get gfNote => l.gfNote;

  @override
  String get gfArrow => l.gfArrow;

  @override
  String get gfLightItBelongsTo => l.gfLightItBelongsTo;

  @override
  String get gfPartItBelongsTo => l.gfPartItBelongsTo;

  @override
  String gfNotANumber(String name) => l.gfNotANumber(name);

  @override
  String get gfFrameEnclosesNothing => l.gfFrameEnclosesNothing;

  @override
  String gfEnclosesNothing(String name) => l.gfEnclosesNothing(name);

  @override
  String get gfSidesCross => l.gfSidesCross;

  @override
  String gfSideCrosses(String first, String second) => l.gfSideCrosses(first, second);

  @override
  String get gfFrameTouchesItself => l.gfFrameTouchesItself;

  @override
  String gfCrossesItself(String name) => l.gfCrossesItself(name);

  @override
  String gfNotConnected(String name) => l.gfNotConnected(name);

  @override
  String gfOutsideFrame(String name) => l.gfOutsideFrame(name);

  @override
  String gfNotOnLeaf(String name) => l.gfNotOnLeaf(name);

  @override
  String gfLiesOutside(String name, String within) => l.gfLiesOutside(name, within);

  @override
  String gfReachesOutside(String name, String within) => l.gfReachesOutside(name, within);

  @override
  String gfLostRegion(String name) => l.gfLostRegion(name);

  @override
  String gfMarkOutside(String name) => l.gfMarkOutside(name);

  @override
  String get gfDimensionNothing => l.gfDimensionNothing;

  @override
  String gfDimensionNotSize(String size) => l.gfDimensionNotSize(size);

  @override
  String gfDimensionDisagrees(String stated, String measured) => l.gfDimensionDisagrees(stated, measured);

  @override
  String get gfDimensionMismatch => l.gfDimensionMismatch;

  @override
  String get gfTitleAttention => l.gfTitleAttention;

  @override
  String get gfTitleReview => l.gfTitleReview;

  @override
  String get gfSummaryError => l.gfSummaryError;

  @override
  String get gfSummaryWarning => l.gfSummaryWarning;

  @override
  String get whyIncompleteOne => l.whyIncompleteOne;

  @override
  String whyIncompleteMany(int n) => l.whyIncompleteMany(n);

  @override
  String get whyCannotOne => l.whyCannotOne;

  @override
  String whyCannotMany(int n) => l.whyCannotMany(n);

  @override
  String get whyCalculateOne => l.whyCalculateOne;

  @override
  String whyCalculateMany(int n) => l.whyCalculateMany(n);

  @override
  String get listComma => l.listComma;

  @override
  String get sentenceStop => l.sentenceStop;

  @override
  String whyExtraOne(String currencies, String currency) => l.whyExtraOne(currencies, currency);

  @override
  String whyExtraMany(int n, String currencies, String currency) => l.whyExtraMany(n, currencies, currency);

  @override
  String get payNothingToPay => l.payNothingToPay;

  @override
  String get payPricingIncomplete => l.payPricingIncomplete;

  @override
  String get payOutstanding => l.payOutstanding;

  @override
  String get payPaidInFull => l.payPaidInFull;

  @override
  String get payCredit => l.payCredit;

  @override
  String get capGroupCustomers => l.capGroupCustomers;

  @override
  String get capGroupDesigns => l.capGroupDesigns;

  @override
  String get capGroupPricing => l.capGroupPricing;

  @override
  String get capGroupFinances => l.capGroupFinances;

  @override
  String get capGroupDiscounts => l.capGroupDiscounts;

  @override
  String get capGroupQuotations => l.capGroupQuotations;

  @override
  String get capGroupPayments => l.capGroupPayments;

  @override
  String get capGroupReceipts => l.capGroupReceipts;

  @override
  String get capGroupExtras => l.capGroupExtras;

  @override
  String get capGroupStaff => l.capGroupStaff;

  @override
  String get capView => l.capView;

  @override
  String get capAdd => l.capAdd;

  @override
  String get capEdit => l.capEdit;

  @override
  String get capDelete => l.capDelete;

  @override
  String get capCreate => l.capCreate;

  @override
  String get capEditAndDraw => l.capEditAndDraw;

  @override
  String get capViewPrices => l.capViewPrices;

  @override
  String get capEditFactoryPrices => l.capEditFactoryPrices;

  @override
  String get capViewSummary => l.capViewSummary;

  @override
  String get capApplyAndChange => l.capApplyAndChange;

  @override
  String get capChangeStatus => l.capChangeStatus;

  @override
  String get capViewHistory => l.capViewHistory;

  @override
  String get capRecordPayments => l.capRecordPayments;

  @override
  String get capRecordRefunds => l.capRecordRefunds;

  @override
  String get capIssue => l.capIssue;

  @override
  String get capRemove => l.capRemove;

  @override
  String get capAddEditStaff => l.capAddEditStaff;

  @override
  String get capChangePermissions => l.capChangePermissions;

  @override
  String get roleOwner => l.roleOwner;

  @override
  String get roleStaff => l.roleStaff;

  @override
  String get roleNobody => l.roleNobody;

  @override
  String deniedPriceList(String who) => l.deniedPriceList(who);

  @override
  String deniedAction(String who, String action, String key) => l.deniedAction(who, action, key);

  @override
  String get storeCustomerGone => l.storeCustomerGone;

  @override
  String get hasDesignOne => l.hasDesignOne;

  @override
  String hasDesignMany(int n) => l.hasDesignMany(n);

  @override
  String get hasPaymentOne => l.hasPaymentOne;

  @override
  String hasPaymentMany(int n) => l.hasPaymentMany(n);

  @override
  String get hasReceiptOne => l.hasReceiptOne;

  @override
  String hasReceiptMany(int n) => l.hasReceiptMany(n);

  @override
  String get hasDiscount => l.hasDiscount;

  @override
  String get hasQuotations => l.hasQuotations;

  @override
  String get hasExtraOne => l.hasExtraOne;

  @override
  String hasExtraMany(int n) => l.hasExtraMany(n);

  @override
  String cannotDeleteCustomer(String name, String has) => l.cannotDeleteCustomer(name, has);

  @override
  String get quotationGone => l.quotationGone;

  @override
  String get staffNameNeeded => l.staffNameNeeded;

  @override
  String get staffNameTaken => l.staffNameTaken;

  @override
  String pinTooShort(int n) => l.pinTooShort(n);

  @override
  String copyOf(String name) => l.copyOf(name);

  @override
  String get nameProblem => l.nameProblem;

  @override
  String qSymbolPrompt(String glyph) => l.qSymbolPrompt(glyph);

  @override
  String get qSymbolDetail => l.qSymbolDetail;

  @override
  String qSymbolOpen(String meaning) => l.qSymbolOpen(meaning);

  @override
  String get qNotASymbol => l.qNotASymbol;

  @override
  String get qNotASymbolDetail => l.qNotASymbolDetail;

  @override
  String get meanPointsLeft => l.meanPointsLeft;

  @override
  String get meanPointsRight => l.meanPointsRight;

  @override
  String get meanPointsUp => l.meanPointsUp;

  @override
  String get meanPointsDown => l.meanPointsDown;

  @override
  String get whereUpper => l.whereUpper;

  @override
  String get whereLower => l.whereLower;

  @override
  String get whereLeft => l.whereLeft;

  @override
  String get whereRight => l.whereRight;

  @override
  String whereBoth(String vertical, String horizontal) => l.whereBoth(vertical, horizontal);

  @override
  String sectionDescribed(String place, String size) => l.sectionDescribed(place, size);

  @override
  String get gapBottom => l.gapBottom;

  @override
  String get gapTop => l.gapTop;

  @override
  String get gapLeft => l.gapLeft;

  @override
  String get gapRight => l.gapRight;

  @override
  String get gapOne => l.gapOne;

  @override
  String qGapPrompt(String side) => l.qGapPrompt(side);

  @override
  String get qGapDetail => l.qGapDetail;

  @override
  String get qKeepOpen => l.qKeepOpen;

  @override
  String qKeepOpenDetail(String side) => l.qKeepOpenDetail(side);

  @override
  String qKeepOpenFootDetail(String side) => l.qKeepOpenFootDetail(side);

  @override
  String get qCloseIt => l.qCloseIt;

  @override
  String qCloseItDetail(String side) => l.qCloseItDetail(side);

  @override
  String get qChangeIt => l.qChangeIt;

  @override
  String get qChangeItDetail => l.qChangeItDetail;

  @override
  String get qNotClosedPrompt => l.qNotClosedPrompt;

  @override
  String get qNotClosedDetail => l.qNotClosedDetail;

  @override
  String get qDrawRest => l.qDrawRest;

  @override
  String get qDrawRestDetail => l.qDrawRestDetail;

  @override
  String qKindPrompt(String opening) => l.qKindPrompt(opening);

  @override
  String get qKindDetail => l.qKindDetail;

  @override
  String get qKindDoorDetail => l.qKindDoorDetail;

  @override
  String get qKindWindowDetail => l.qKindWindowDetail;

  @override
  String get qConstructionDoor => l.qConstructionDoor;

  @override
  String get qConstructionDesign => l.qConstructionDesign;

  @override
  String get qConstructionDetail => l.qConstructionDetail;

  @override
  String get qOnePart => l.qOnePart;

  @override
  String get qOnePartDetail => l.qOnePartDetail;

  @override
  String get qParts => l.qParts;

  @override
  String get qPartsDetail => l.qPartsDetail;

  @override
  String partNumbered(int number) => l.partNumbered(number);

  @override
  String get partFixed => l.partFixed;

  @override
  String get payLegacyNote => l.payLegacyNote;

  @override
  String get amtEnter => l.amtEnter;

  @override
  String get amtMoreThanNothing => l.amtMoreThanNothing;

  @override
  String get amtToTheCent => l.amtToTheCent;

  @override
  String get amtAsNumber => l.amtAsNumber;

  @override
  String get amtSmaller => l.amtSmaller;

  @override
  String get refundNothingPaid => l.refundNothingPaid;

  @override
  String refundNothingPaidIn(String currency) => l.refundNothingPaidIn(currency);

  @override
  String refundTooMuch(String amount) => l.refundTooMuch(amount);

  @override
  String get paymentNotFuture => l.paymentNotFuture;

  @override
  String get refundNotFuture => l.refundNotFuture;

  @override
  String get rateAsNumber => l.rateAsNumber;

  @override
  String get rateMoreThanNothing => l.rateMoreThanNothing;

  @override
  String get discountNone => l.discountNone;

  @override
  String get discountEnter => l.discountEnter;

  @override
  String get discountMoreThanNothing => l.discountMoreThanNothing;

  @override
  String get discountOver100 => l.discountOver100;

  @override
  String get discountNotFinal => l.discountNotFinal;

  @override
  String discountOverSubtotal(String amount) => l.discountOverSubtotal(amount);

  @override
  String get discountPercentNumber => l.discountPercentNumber;

  @override
  String get qsDraft => l.qsDraft;

  @override
  String get qsIssued => l.qsIssued;

  @override
  String get qsAccepted => l.qsAccepted;

  @override
  String get qsRejected => l.qsRejected;

  @override
  String get qsExpired => l.qsExpired;

  @override
  String get quoteIncomplete => l.quoteIncomplete;

  @override
  String get quoteChooseOne => l.quoteChooseOne;

  @override
  String quoteNotReady(String message, String names) => l.quoteNotReady(message, names);

  @override
  String quoteExtraCurrency(String name, String currency, String base) => l.quoteExtraCurrency(name, currency, base);

  @override
  String quoteDiscountExceeds(String discount, String subtotal) => l.quoteDiscountExceeds(discount, subtotal);

  @override
  String quoteCannotBecome(String status, String next) => l.quoteCannotBecome(status, next);

  @override
  String get xcMaterial => l.xcMaterial;

  @override
  String get xcLabour => l.xcLabour;

  @override
  String get xcService => l.xcService;

  @override
  String get xcTransport => l.xcTransport;

  @override
  String get xcInstallation => l.xcInstallation;

  @override
  String get xcOther => l.xcOther;

  @override
  String get xuPiece => l.xuPiece;

  @override
  String get xuPieces => l.xuPieces;

  @override
  String get xuBottle => l.xuBottle;

  @override
  String get xuBottles => l.xuBottles;

  @override
  String get xuHour => l.xuHour;

  @override
  String get xuHours => l.xuHours;

  @override
  String get xuMetre => l.xuMetre;

  @override
  String get xuMetres => l.xuMetres;

  @override
  String get xuSquareMetre => l.xuSquareMetre;

  @override
  String get xuSquareMetres => l.xuSquareMetres;

  @override
  String get xuKg => l.xuKg;

  @override
  String get xuKgs => l.xuKgs;

  @override
  String get xuSet => l.xuSet;

  @override
  String get xuSets => l.xuSets;

  @override
  String get xuRoll => l.xuRoll;

  @override
  String get xuRolls => l.xuRolls;

  @override
  String get xuDay => l.xuDay;

  @override
  String get xuDays => l.xuDays;

  @override
  String get xuTrip => l.xuTrip;

  @override
  String get xuTrips => l.xuTrips;

  @override
  String get xNameNeeded => l.xNameNeeded;

  @override
  String get xQtyEnter => l.xQtyEnter;

  @override
  String get xQtyMore => l.xQtyMore;

  @override
  String get xUnitNeeded => l.xUnitNeeded;

  @override
  String get xPriceEnter => l.xPriceEnter;

  @override
  String get xPriceNotBelow => l.xPriceNotBelow;

  @override
  String get xQtyNumber => l.xQtyNumber;

  @override
  String get xQtyPlaces => l.xQtyPlaces;

  @override
  String get xPriceNumber => l.xPriceNumber;

  @override
  String get xPricePlaces => l.xPricePlaces;

  @override
  String xAlreadyOne(String what) => l.xAlreadyOne(what);

  @override
  String xAlreadyMany(String what) => l.xAlreadyMany(what);

  @override
  String xAlreadyItem(String what, String amount) => l.xAlreadyItem(what, amount);

  @override
  String ppPercentOf(String percent, String amount) => l.ppPercentOf(percent, amount);

  @override
  String get ppFixed => l.ppFixed;

  @override
  String get ccEnterFigure => l.ccEnterFigure;

  @override
  String get ccRateNotBelow => l.ccRateNotBelow;

  @override
  String get ccNameRequired => l.ccNameRequired;

  @override
  String get ccChooseMaterial => l.ccChooseMaterial;

  @override
  String ccNoProfile(String material) => l.ccNoProfile(material);

  @override
  String ccRateRequired(String material) => l.ccRateRequired(material);

  @override
  String ccNameTaken(String name, String material) => l.ccNameTaken(name, material);

  @override
  String get ccNotInList => l.ccNotInList;

  @override
  String get rfNeeded => l.rfNeeded;

  @override
  String get rfZeroOrMore => l.rfZeroOrMore;

  @override
  String get rfWhole => l.rfWhole;

  @override
  String get rfGlassSingle => l.rfGlassSingle;

  @override
  String get rfSealed => l.rfSealed;

  @override
  String get rfPanel => l.rfPanel;

  @override
  String get rfAnyOtherColour => l.rfAnyOtherColour;

  @override
  String get rfHardware => l.rfHardware;

  @override
  String get rfSliding => l.rfSliding;

  @override
  String get rfTrack => l.rfTrack;

  @override
  String get rfRoller => l.rfRoller;

  @override
  String get rfRollersPerPanel => l.rfRollersPerPanel;

  @override
  String get rfInstallation => l.rfInstallation;

  @override
  String get rfEachDesign => l.rfEachDesign;

  @override
  String get rfByArea => l.rfByArea;

  @override
  String get rfBorderLines => l.rfBorderLines;

  @override
  String get rfOpeningProfile => l.rfOpeningProfile;

  @override
  String rfAnyOtherColourOf(String material) => l.rfAnyOtherColourOf(material);

  @override
  String get rfAMetre => l.rfAMetre;

  @override
  String get rfOnProfile => l.rfOnProfile;

  @override
  String rfLabourOf(String category) => l.rfLabourOf(category);

  @override
  String get rfOnMaterials => l.rfOnMaterials;

  @override
  String get rfUnitEach => l.rfUnitEach;

  @override
  String get rfUnitFixed => l.rfUnitFixed;

  @override
  String get rfUnitRollers => l.rfUnitRollers;

  @override
  String get discountDesignNotFinal => l.discountDesignNotFinal;

  @override
  String get dimOverall => l.dimOverall;

  @override
  String get dimDaylight => l.dimDaylight;

  @override
  String get dimOpening => l.dimOpening;

  @override
  String get dimDivision => l.dimDivision;

  @override
  String get dimSide => l.dimSide;

  @override
  String get dimOverallWidth => l.dimOverallWidth;

  @override
  String get dimOverallHeight => l.dimOverallHeight;

  @override
  String dimKindWidth(String what) => l.dimKindWidth(what);

  @override
  String dimKindHeight(String what) => l.dimKindHeight(what);

  @override
  String get dimSectionWidth => l.dimSectionWidth;

  @override
  String get dimSectionHeight => l.dimSectionHeight;

  @override
  String get dimRealSize => l.dimRealSize;

  @override
  String get cadGlass => l.cadGlass;

  @override
  String cadLookGlass(String look) => l.cadLookGlass(look);

  @override
  String get cadIn => l.cadIn;

  @override
  String get cadOut => l.cadOut;

  @override
  String get msTooWide => l.msTooWide;

  @override
  String get msBarThickness => l.msBarThickness;

  @override
  String get msSmallerThanFrame => l.msSmallerThanFrame;

  @override
  String get msNotFitInside => l.msNotFitInside;

  @override
  String get msNotFitBeside => l.msNotFitBeside;

  @override
  String get msNothing => l.msNothing;

  @override
  String get msNotFit => l.msNotFit;

  @override
  String get msNoFrame => l.msNoFrame;

  @override
  String mnAluminium(String rate) => l.mnAluminium(rate);

  @override
  String mnBarRate(String material, String bar, String frame) => l.mnBarRate(material, bar, frame);

  @override
  String mnLeaf(String each) => l.mnLeaf(each);

  @override
  String mnJoint(String joint) => l.mnJoint(joint);

  @override
  String get mnSealed => l.mnSealed;

  @override
  String get mnCatalog => l.mnCatalog;

}
