// Generated by tool/generate_domain_words.dart from lib/app/l10n/app_en.arb.
// Do not edit: change the ARB entry and run the tool again.
// dart format off

/// What the domain says to the user, one method a message.
///
/// The domain composes its sentences through these, so the
/// application can have them in whichever language is shown;
/// [EnglishWords] is the English, which is also what every
/// domain object says when nobody asks for another language.
abstract interface class Words {
  /// Design category: a door.
  String get kindDoor;

  /// Design category: a window.
  String get kindWindow;

  /// Design category: doors and windows in one frame.
  String get kindBoth;

  /// Design category: sliding panels.
  String get kindSliding;

  /// Design category: sloped, under-stair and custom shapes.
  String get kindAngled;

  /// A category this version does not know.
  String get kindUnsupported;

  /// A door, in the middle of a sentence.
  String get nounDoor;

  /// A window, in the middle of a sentence.
  String get nounWindow;

  /// A door and window design, in the middle of a sentence.
  String get nounBoth;

  /// A sliding design, in the middle of a sentence.
  String get nounSliding;

  /// An angled design, in the middle of a sentence.
  String get nounAngled;

  /// A design of an unknown category, in the middle of a sentence.
  String get nounUnsupported;

  /// A design with no name, e.g. 'Untitled window'.
  String untitledDesign(String noun);

  /// What a door is built of: not said yet.
  String get constructionPending;

  /// Built of panel.
  String get constructionPanel;

  /// Built of glass.
  String get constructionGlass;

  /// Built of panel and glass.
  String get constructionBoth;

  /// Material: uPVC profile (kept as the trade name).
  String get matUpvc;

  /// Material: aluminium.
  String get matAluminium;

  /// Material: wood.
  String get matWood;

  /// Material: steel.
  String get matSteel;

  /// Material: clear glass.
  String get matClearGlass;

  /// Material: frosted (obscured) glass.
  String get matFrostedGlass;

  /// Material: tinted glass.
  String get matTintedGlass;

  /// Material: a solid (opaque) panel.
  String get matPanel;

  /// Material: louvre slats.
  String get matLouvre;

  /// Material: insect mesh.
  String get matMesh;

  /// Material: rubber gasket.
  String get matRubber;

  /// Material class: glass.
  String get classGlass;

  /// Material class: panel.
  String get classPanel;

  /// Material class: PVC.
  String get classPvc;

  /// Material class: aluminium.
  String get classAluminium;

  /// Material class: wood.
  String get classWood;

  /// Material class: rubber.
  String get classRubber;

  /// Material class: metal.
  String get classMetal;

  /// Material class: polished metal of a handle.
  String get classHandleMetal;

  /// Material class: satin metal of a hinge.
  String get classHingeMetal;

  /// Material class: mesh.
  String get classMesh;

  /// Colour name.
  String get colourBlack;

  /// Colour name.
  String get colourWhite;

  /// Colour name.
  String get colourSilver;

  /// Colour name.
  String get colourGrey;

  /// Colour name.
  String get colourBronze;

  /// Colour name.
  String get colourBrown;

  /// Colour name: a white with a little grey.
  String get colourOffWhite;

  /// Colour name.
  String get colourCream;

  /// Colour name: a very dark grey.
  String get colourGraphite;

  /// Colour name.
  String get colourDeepGreen;

  /// Colour name.
  String get colourSteelBlue;

  /// Colour name: the colour of oak wood.
  String get colourOak;

  /// Colour name: the colour of walnut wood.
  String get colourWalnut;

  /// Colour name: a deep dark red.
  String get colourOxblood;

  /// Colour name: the colour of clear glass.
  String get colourClearGlass;

  /// Colour name: frosted glass.
  String get colourFrosted;

  /// Colour name.
  String get colourWarmCream;

  /// Glass look: clear.
  String get glassClear;

  /// Glass look: tinted.
  String get glassTinted;

  /// Glass look: frosted.
  String get glassFrosted;

  /// Glass look: dark tinted.
  String get glassDark;

  /// Glass look: blue-grey tinted.
  String get glassBlueGrey;

  /// How a section opens: it does not.
  String get mechFixed;

  /// Explains Fixed.
  String get mechFixedHint;

  /// How a section opens: hinged on the left.
  String get mechHingedLeft;

  /// Explains Hinged left.
  String get mechHingedLeftHint;

  /// How a section opens: hinged on the right.
  String get mechHingedRight;

  /// Explains Hinged right.
  String get mechHingedRightHint;

  /// How a section opens: hinged at the top.
  String get mechTopHung;

  /// Explains Top hung.
  String get mechTopHungHint;

  /// How a section opens: hinged at the bottom.
  String get mechBottomHung;

  /// Explains Bottom hung.
  String get mechBottomHungHint;

  /// How a section opens: slides to the left.
  String get mechSlidingLeft;

  /// Explains Sliding left.
  String get mechSlidingLeftHint;

  /// How a section opens: slides to the right.
  String get mechSlidingRight;

  /// Explains Sliding right.
  String get mechSlidingRightHint;

  /// How a section opens: tilt and turn.
  String get mechTiltAndTurn;

  /// Explains Tilt and turn.
  String get mechTiltAndTurnHint;

  /// How a section opens: folds in leaves.
  String get mechBifold;

  /// Explains Bi-fold.
  String get mechBifoldHint;

  /// How a section opens: turns about a central axis.
  String get mechPivot;

  /// Explains Pivot.
  String get mechPivotHint;

  /// Ironmongery: a handle.
  String get hwHandle;

  /// Ironmongery: a lever handle on a backplate.
  String get hwLever;

  /// Ironmongery: a round knob.
  String get hwKnob;

  /// Ironmongery: a lock.
  String get hwLock;

  /// Ironmongery: a hinge.
  String get hwHinge;

  /// Ironmongery: a letter plate.
  String get hwLetterplate;

  /// Ironmongery: a door viewer.
  String get hwPeephole;

  /// Ironmongery: a door closer.
  String get hwCloser;

  /// Ironmongery: the long bar a sliding panel is pulled by.
  String get hwPull;

  /// A pleated insect screen in a cassette.
  String get hwScreen;

  /// The sensor that opens an automatic entrance.
  String get hwSensor;

  /// The frame of the design.
  String get elFrame;

  /// A section of the design.
  String get elSection;

  /// A note written on the drawing.
  String get elNote;

  /// An arrow drawn on the drawing.
  String get elArrow;

  /// An upright line dividing the design.
  String get elVerticalDivider;

  /// A level line dividing the design.
  String get elHorizontalDivider;

  /// A sloped line dividing the design.
  String get elAngledDivider;

  /// Money received from the customer.
  String get payTypePayment;

  /// Money returned to the customer.
  String get payTypeRefund;

  /// Payment method.
  String get payCash;

  /// Payment method.
  String get payBankTransfer;

  /// Payment method.
  String get payCard;

  /// Payment method: another way.
  String get payOther;

  /// Payment method of a payment brought over from before the ledger.
  String get payLegacy;

  /// A payment method described by the user.
  String payOtherDetail(String detail);

  /// A discount as a percentage.
  String get discountPercent;

  /// A discount as a fixed amount of money.
  String get discountFixed;

  /// 3D projection as the eye sees it.
  String get projectionPerspective;

  /// 3D projection keeping parallel edges parallel.
  String get projectionParallel;

  /// Price group: the frame's border and the lines inside the design.
  String get groupNormalProfile;

  /// Price group: the profile round each opening.
  String get groupOpeningProfile;

  /// Price group: other profile by the metre, a sliding track.
  String get groupOtherProfile;

  /// Price group: what a colour adds.
  String get groupColour;

  /// Price group: glass.
  String get groupGlass;

  /// Price group: panel.
  String get groupPanel;

  /// Price group: handles, hinges, locks.
  String get groupHardware;

  /// Price group: labour.
  String get groupLabour;

  /// Price group: installation.
  String get groupInstallation;

  /// Price unit: counted by the piece.
  String get unitEach;

  /// Glass row: the design has glass, not included in the price.
  String get glassNotIncluded;

  /// Glass row: included, but no glass to charge.
  String get glassNothingToCharge;

  /// A material the design does not use.
  String get glassNotUsed;

  /// Aluminium profile category: System Aluminium.
  String get catSystemAluminium;

  /// Aluminium profile category: Bend Shoulder Aluminium (product term, kept in English pending review).
  String get catBendShoulderAluminium;

  /// The frame's border profile.
  String get partBorder;

  /// The lines inside the design, cut from the same profile.
  String get partLines;

  /// An opening (a part of the design that opens) by its number across the drawing.
  String openingNumbered(int number);

  /// An opening, where it has no number.
  String get openingAlone;

  /// The opening, in a sentence.
  String get openingThe;

  /// A part of the design, in a sentence.
  String get partA;

  /// The top member of a frame.
  String get placeHead;

  /// The bottom member of a frame.
  String get placeSill;

  /// The left upright member of a frame.
  String get placeLeftJamb;

  /// The right upright member of a frame.
  String get placeRightJamb;

  /// A sloping side of a frame, upper left.
  String get placeRakingUpperLeft;

  /// A sloping side of a frame, upper right.
  String get placeRakingUpperRight;

  /// A sloping side of a frame, lower left.
  String get placeRakingLowerLeft;

  /// A sloping side of a frame, lower right.
  String get placeRakingLowerRight;

  /// A line of the design by its number.
  String lineNumbered(int n);

  /// A line drawn inside an opening.
  String lineInside(int n, String opening);

  /// Size: the width of the frame's border profile.
  String get measFrameBorder;

  /// Size: the thickness of the lines dividing the design.
  String get measBarThickness;

  /// Size: the whole design's width.
  String get measOverallWidth;

  /// Size: the whole design's height.
  String get measOverallHeight;

  /// A width.
  String get axisWidth;

  /// A height.
  String get axisHeight;

  /// A part of the design that does not open, by its number.
  String measFixedLight(int n);

  /// A pane inside a part: the part, what fills the pane, and its number.
  String measPane(String around, String material, int n);

  /// The height of one side of an angled frame.
  String sideHeight(String side);

  /// The width of one side of an angled frame.
  String sideWidth(String side);

  /// Two things joined: a and b.
  String joinAnd(String a, String b);

  /// Two things offered: a or b.
  String joinOr(String a, String b);

  /// Why a design cannot be priced.
  String get reqUnsupported;

  /// Why a design cannot be priced: lines drawn since the last reading.
  String get reqNotRead;

  /// Why a design cannot be priced.
  String get reqFrame;

  /// Why a design cannot be priced.
  String get reqDraw;

  /// Why a design cannot be priced, with the geometry problem.
  String reqGeometry(String problem);

  /// Why a door cannot be priced.
  String get reqConstruction;

  /// Why a design cannot be priced.
  String get reqPanelOrGlass;

  /// Why a design cannot be priced.
  String reqOpeningKind(String opening);

  /// Why a design cannot be priced: sizes of the frame not given.
  String reqFrameSizes(String which);

  /// Why a design cannot be priced: sizes of one part not given.
  String reqGroupSizes(String group, String which);

  /// Why a design cannot be priced.
  String get reqProfile;

  /// Why an aluminium design cannot be priced: no profile category chosen.
  String reqCategoryAll(String material, String choices);

  /// Why an aluminium design cannot be priced: some parts have no category.
  String reqCategorySome(String choices, String parts);

  /// The first missing thing, and how many more (one).
  String readinessMoreOne(String first, int more);

  /// The first missing thing, and how many more (several).
  String readinessMoreMany(String first, int more);

  /// Why a design cannot be measured.
  String get takeoffNothing;

  /// Why a design cannot be measured.
  String get takeoffOutline;

  /// Why a design cannot be measured.
  String get takeoffNoSize;

  /// The chosen colour is not sold in this material.
  String colourNotForMaterial(String material);

  /// The price list has no rate for this colour on this material.
  String colourNotConfigured(String material);

  /// The chosen colour is retired or unknown.
  String get colourUnavailable;

  /// The price list has no price for this material.
  String colourNoProfile(String material);

  /// A colour the factory stocks as standard.
  String get gradeStandard;

  /// A colour the factory sells at a surcharge.
  String get gradeNonStandard;

  /// A colour the price list does not name.
  String get gradeSpecial;

  /// Why a design cannot be priced.
  String get engineUnsupported;

  /// Why a design cannot be priced.
  String engineNoCategory(String kind);

  /// Something the price list has no rate for.
  String engineMissing(String what);

  /// An extra charge in another currency than the price list's.
  String engineExtraCurrency(String name, String currency, String listCurrency);

  /// What the price list lacks: a material's profile.
  String missProfile(String material);

  /// What the price list lacks: border and lines of a material or category.
  String missBorderLines(String what);

  /// What the price list lacks: an infill material.
  String missInfill(String material);

  /// What the price list lacks: a piece of ironmongery.
  String missPiece(String piece);

  /// A colour or glass of the user's own, not one of the named ones.
  String get custom;

  /// Nothing chosen yet.
  String get notSelected;

  /// A price line: a material or category, and border or internal lines.
  String lineProfile(String what, String part);

  /// A price line: the opening profile of a material.
  String lineOpeningProfile(String material);

  /// A price line: what a colour adds to a material's profile.
  String lineColour(String colour, String material, String grade);

  /// A price line: the track sliding panels run on.
  String get lineTrack;

  /// A price line: glass of a look.
  String lineGlass(String look);

  /// A price line: a sealed double-glazed unit.
  String lineSealed(String glass);

  /// A price line: a panel of a colour.
  String linePanel(String colour);

  /// A price line: several pieces of ironmongery (English adds an s).
  String linePieces(String piece);

  /// A price line: the rollers sliding panels run on.
  String get lineRollers;

  /// A price line: the labour of making.
  String get lineMaking;

  /// A price line: labour priced by area.
  String get lineMakingArea;

  /// A price line: labour as a share of the materials.
  String get lineMakingMaterials;

  /// A price line: installation.
  String get lineInstallation;

  /// A price line: installation by area.
  String get lineInstallationArea;

  /// A design's card: lines drawn and not read.
  String get stateNotRead;

  /// A design that can be priced.
  String get stateComplete;

  /// A design that cannot be priced yet.
  String get stateIncomplete;

  /// Where the price would be.
  String get noteNotRead;

  /// Where the price would be.
  String get noteNotCalculated;

  /// Where the price would be: the design or prices changed.
  String get noteRecalculate;

  /// Where the price would be.
  String get noteIncomplete;

  /// Where the price would be.
  String get noteUnavailable;

  /// Why the kept price is not current.
  String get msgRecalculate;

  /// A design that can be priced and has not been.
  String get msgCalculate;

  /// Why a design of an unknown category has no price.
  String get reasonUnsupported;

  /// Why a design has no price.
  String get reasonListCannot;

  /// Geometry check: a part with no name.
  String get gfPartOfDesign;

  /// Geometry check: the frame.
  String get gfFrame;

  /// Geometry check: one side of the frame.
  String gfMemberOfFrame(String member);

  /// Geometry check: a line inside an opening or a light.
  String gfLineInside(String parent);

  /// Geometry check: a line dividing the design.
  String get gfBar;

  /// Geometry check: an upright dividing line.
  String get gfMullion;

  /// Geometry check: a level dividing line.
  String get gfTransom;

  /// Geometry check: a sloping dividing line.
  String get gfSlopedBar;

  /// Geometry check: a pane inside an opening.
  String gfPaneOf(String parent);

  /// Geometry check: the region an opening fills.
  String gfRegionOf(String opening);

  /// Geometry check: a part that does not open.
  String get gfFixedLight;

  /// Geometry check: a piece of ironmongery of an opening.
  String gfPieceOf(String piece, String opening);

  /// Geometry check: a piece of ironmongery.
  String gfPiece(String piece);

  /// Geometry check: a dimension the user stated.
  String gfDimensionGiven(String size);

  /// Geometry check: a dimension.
  String get gfDimension;

  /// Geometry check: a note.
  String get gfNote;

  /// Geometry check: an arrow.
  String get gfArrow;

  /// Geometry check: the light a child belongs to.
  String get gfLightItBelongsTo;

  /// Geometry check: the part a child belongs to.
  String get gfPartItBelongsTo;

  /// Geometry check message.
  String gfNotANumber(String name);

  /// Geometry check message.
  String get gfFrameEnclosesNothing;

  /// Geometry check message.
  String gfEnclosesNothing(String name);

  /// Geometry check message.
  String get gfSidesCross;

  /// Geometry check message: two named sides cross.
  String gfSideCrosses(String first, String second);

  /// Geometry check message.
  String get gfFrameTouchesItself;

  /// Geometry check message.
  String gfCrossesItself(String name);

  /// Geometry check message.
  String gfNotConnected(String name);

  /// Geometry check message.
  String gfOutsideFrame(String name);

  /// Geometry check message: a hinge or handle off the leaf it belongs to.
  String gfNotOnLeaf(String name);

  /// Geometry check message.
  String gfLiesOutside(String name, String within);

  /// Geometry check message.
  String gfReachesOutside(String name, String within);

  /// Geometry check message.
  String gfLostRegion(String name);

  /// Geometry check message.
  String gfMarkOutside(String name);

  /// Geometry check message.
  String get gfDimensionNothing;

  /// Geometry check message.
  String gfDimensionNotSize(String size);

  /// Geometry check message.
  String gfDimensionDisagrees(String stated, String measured);

  /// Geometry check message.
  String get gfDimensionMismatch;

  /// Heading of the geometry check where there is an error.
  String get gfTitleAttention;

  /// Heading of the geometry check where there are only warnings.
  String get gfTitleReview;

  /// Under the geometry check heading where there is an error.
  String get gfSummaryError;

  /// Under the geometry check heading where there are only warnings.
  String get gfSummaryWarning;

  /// Why a customer's total is not final.
  String get whyIncompleteOne;

  /// Why a customer's total is not final.
  String whyIncompleteMany(int n);

  /// Why a customer's total is not final.
  String get whyCannotOne;

  /// Why a customer's total is not final.
  String whyCannotMany(int n);

  /// Why a customer's total is not final.
  String get whyCalculateOne;

  /// Why a customer's total is not final.
  String whyCalculateMany(int n);

  /// What separates items in a list, with its space.
  String get listComma;

  /// The full stop that ends a sentence.
  String get sentenceStop;

  /// Why a customer's total is not final: an extra in another currency.
  String whyExtraOne(String currencies, String currency);

  /// Why a customer's total is not final: extras in another currency.
  String whyExtraMany(int n, String currencies, String currency);

  /// A customer's money: nothing to pay.
  String get payNothingToPay;

  /// A customer's money: the total is not final yet.
  String get payPricingIncomplete;

  /// A customer's money: some is still due.
  String get payOutstanding;

  /// A customer's money: all paid.
  String get payPaidInFull;

  /// A customer's money: paid more than the total; the customer has credit.
  String get payCredit;

  /// Permission group.
  String get capGroupCustomers;

  /// Permission group.
  String get capGroupDesigns;

  /// Permission group.
  String get capGroupPricing;

  /// Permission group.
  String get capGroupFinances;

  /// Permission group.
  String get capGroupDiscounts;

  /// Permission group.
  String get capGroupQuotations;

  /// Permission group.
  String get capGroupPayments;

  /// Permission group.
  String get capGroupReceipts;

  /// Permission group.
  String get capGroupExtras;

  /// Permission group.
  String get capGroupStaff;

  /// Permission: view.
  String get capView;

  /// Permission: add.
  String get capAdd;

  /// Permission: edit.
  String get capEdit;

  /// Permission: delete.
  String get capDelete;

  /// Permission: create.
  String get capCreate;

  /// Permission: edit and draw designs.
  String get capEditAndDraw;

  /// Permission.
  String get capViewPrices;

  /// Permission.
  String get capEditFactoryPrices;

  /// Permission: see a customer's financial summary.
  String get capViewSummary;

  /// Permission: give and change discounts.
  String get capApplyAndChange;

  /// Permission: change a quotation's status.
  String get capChangeStatus;

  /// Permission: see the payment history.
  String get capViewHistory;

  /// Permission.
  String get capRecordPayments;

  /// Permission.
  String get capRecordRefunds;

  /// Permission: issue receipts.
  String get capIssue;

  /// Permission: remove extra charges.
  String get capRemove;

  /// Permission.
  String get capAddEditStaff;

  /// Permission.
  String get capChangePermissions;

  /// Who is signed in: the workshop's owner.
  String get roleOwner;

  /// Who is at the device: staff.
  String get roleStaff;

  /// Who is at the device: nobody signed in.
  String get roleNobody;

  /// Refusal: somebody else tried to change the price list.
  String deniedPriceList(String who);

  /// Refusal: a permission somebody does not hold. The key is the permission's code.
  String deniedAction(String who, String action, String key);

  /// A customer that has been removed.
  String get storeCustomerGone;

  /// What a customer has: one design.
  String get hasDesignOne;

  /// What a customer has: designs.
  String hasDesignMany(int n);

  /// What a customer has: one payment.
  String get hasPaymentOne;

  /// What a customer has: payments.
  String hasPaymentMany(int n);

  /// What a customer has: one receipt.
  String get hasReceiptOne;

  /// What a customer has: receipts.
  String hasReceiptMany(int n);

  /// What a customer has: a discount.
  String get hasDiscount;

  /// What a customer has: quotations.
  String get hasQuotations;

  /// What a customer has: one extra charge.
  String get hasExtraOne;

  /// What a customer has: extra charges.
  String hasExtraMany(int n);

  /// Why a customer cannot be deleted.
  String cannotDeleteCustomer(String name, String has);

  /// A quotation that is not kept.
  String get quotationGone;

  /// A member of staff with no name.
  String get staffNameNeeded;

  /// A member of staff's name already used.
  String get staffNameTaken;

  /// A PIN that is too short.
  String pinTooShort(int n);

  /// The name of a duplicated design.
  String copyOf(String name);

  /// A design's name left empty.
  String get nameProblem;

  /// Question: a mark drawn outside the design.
  String qSymbolPrompt(String glyph);

  /// Question: a mark drawn outside the design.
  String get qSymbolDetail;

  /// Answer: open this section, and how.
  String qSymbolOpen(String meaning);

  /// Answer: the mark is not an opening mark.
  String get qNotASymbol;

  /// Explains the answer.
  String get qNotASymbolDetail;

  /// What a < mark says.
  String get meanPointsLeft;

  /// What a > mark says.
  String get meanPointsRight;

  /// What a ^ mark says.
  String get meanPointsUp;

  /// What a v mark says.
  String get meanPointsDown;

  /// Where a section is: upper.
  String get whereUpper;

  /// Where a section is: lower.
  String get whereLower;

  /// Where a section is: left.
  String get whereLeft;

  /// Where a section is: right.
  String get whereRight;

  /// Where a section is: e.g. upper left.
  String whereBoth(String vertical, String horizontal);

  /// A section named by where it is and its size.
  String sectionDescribed(String place, String size);

  /// The side of an outline left open: the bottom.
  String get gapBottom;

  /// The side of an outline left open: the top.
  String get gapTop;

  /// The side of an outline left open: the left.
  String get gapLeft;

  /// The side of an outline left open: the right.
  String get gapRight;

  /// The side of an outline left open: unnamed.
  String get gapOne;

  /// Question: one side of the outline left open.
  String qGapPrompt(String side);

  /// Question: one side of the outline left open.
  String get qGapDetail;

  /// Answer: keep the side open.
  String get qKeepOpen;

  /// Explains Keep it open.
  String qKeepOpenDetail(String side);

  /// Explains Keep it open, for the bottom.
  String qKeepOpenFootDetail(String side);

  /// Answer: close the side.
  String get qCloseIt;

  /// Explains Close it.
  String qCloseItDetail(String side);

  /// Answer: the user will change the drawing.
  String get qChangeIt;

  /// Explains I will change it.
  String get qChangeItDetail;

  /// Question: lines that do not close into a shape.
  String get qNotClosedPrompt;

  /// Question: lines that do not close into a shape.
  String get qNotClosedDetail;

  /// Answer: the user will finish the outline.
  String get qDrawRest;

  /// Explains Let me draw the rest.
  String get qDrawRestDetail;

  /// Question: is this opening a door or a window.
  String qKindPrompt(String opening);

  /// Question detail: door or window.
  String get qKindDetail;

  /// Answer detail: a door.
  String get qKindDoorDetail;

  /// Answer detail: a window.
  String get qKindWindowDetail;

  /// Question as a door design starts: panel, glass or both.
  String get qConstructionDoor;

  /// Question as a door & window design starts: panel, glass or both.
  String get qConstructionDesign;

  /// Question detail: what a door is built of.
  String get qConstructionDetail;

  /// Said where a design to be both glass and panel has only one part.
  String get qOnePart;

  /// Detail for the one-part case.
  String get qOnePartDetail;

  /// Question: glass or panel, part by part.
  String get qParts;

  /// Detail of the glass-or-panel question.
  String get qPartsDetail;

  /// A part of the design, by its place in reading order.
  String partNumbered(int number);

  /// Where a part is: a fixed part of the design, in no opening.
  String get partFixed;

  /// Note on the one payment carried over from an older customer record.
  String get payLegacyNote;

  /// Amount check.
  String get amtEnter;

  /// Amount check.
  String get amtMoreThanNothing;

  /// Amount check.
  String get amtToTheCent;

  /// Amount check.
  String get amtAsNumber;

  /// Amount check.
  String get amtSmaller;

  /// Refund check.
  String get refundNothingPaid;

  /// Refund check, in another currency.
  String refundNothingPaidIn(String currency);

  /// Refund check.
  String refundTooMuch(String amount);

  /// Date check for a payment.
  String get paymentNotFuture;

  /// Date check for a refund.
  String get refundNotFuture;

  /// Exchange rate check.
  String get rateAsNumber;

  /// Exchange rate check.
  String get rateMoreThanNothing;

  /// No discount in force.
  String get discountNone;

  /// Discount check.
  String get discountEnter;

  /// Discount check.
  String get discountMoreThanNothing;

  /// Discount check.
  String get discountOver100;

  /// Discount check.
  String get discountNotFinal;

  /// Discount check.
  String discountOverSubtotal(String amount);

  /// Discount check.
  String get discountPercentNumber;

  /// Quotation status.
  String get qsDraft;

  /// Quotation status.
  String get qsIssued;

  /// Quotation status.
  String get qsAccepted;

  /// Quotation status.
  String get qsRejected;

  /// Quotation status.
  String get qsExpired;

  /// Quotation check.
  String get quoteIncomplete;

  /// Quotation check.
  String get quoteChooseOne;

  /// Quotation check, naming the designs.
  String quoteNotReady(String message, String names);

  /// Quotation check.
  String quoteExtraCurrency(String name, String currency, String base);

  /// Quotation check.
  String quoteDiscountExceeds(String discount, String subtotal);

  /// Quotation status check.
  String quoteCannotBecome(String status, String next);

  /// Category of an extra charge.
  String get xcMaterial;

  /// Category of an extra charge.
  String get xcLabour;

  /// Category of an extra charge.
  String get xcService;

  /// Category of an extra charge.
  String get xcTransport;

  /// Category of an extra charge.
  String get xcInstallation;

  /// Category of an extra charge.
  String get xcOther;

  /// Unit of an extra charge, one.
  String get xuPiece;

  /// Unit of an extra charge, more than one.
  String get xuPieces;

  /// Unit of an extra charge, one.
  String get xuBottle;

  /// Unit of an extra charge, more than one.
  String get xuBottles;

  /// Unit of an extra charge, one.
  String get xuHour;

  /// Unit of an extra charge, more than one.
  String get xuHours;

  /// Unit of an extra charge, one.
  String get xuMetre;

  /// Unit of an extra charge, more than one.
  String get xuMetres;

  /// Unit of an extra charge, one.
  String get xuSquareMetre;

  /// Unit of an extra charge, more than one.
  String get xuSquareMetres;

  /// Unit of an extra charge, one.
  String get xuKg;

  /// Unit of an extra charge, more than one.
  String get xuKgs;

  /// Unit of an extra charge, one.
  String get xuSet;

  /// Unit of an extra charge, more than one.
  String get xuSets;

  /// Unit of an extra charge, one.
  String get xuRoll;

  /// Unit of an extra charge, more than one.
  String get xuRolls;

  /// Unit of an extra charge, one.
  String get xuDay;

  /// Unit of an extra charge, more than one.
  String get xuDays;

  /// Unit of an extra charge, one.
  String get xuTrip;

  /// Unit of an extra charge, more than one.
  String get xuTrips;

  /// Extra charge check.
  String get xNameNeeded;

  /// Extra charge check.
  String get xQtyEnter;

  /// Extra charge check.
  String get xQtyMore;

  /// Extra charge check.
  String get xUnitNeeded;

  /// Extra charge check.
  String get xPriceEnter;

  /// Extra charge check.
  String get xPriceNotBelow;

  /// Extra charge check.
  String get xQtyNumber;

  /// Extra charge check.
  String get xQtyPlaces;

  /// Extra charge check.
  String get xPriceNumber;

  /// Extra charge check.
  String get xPricePlaces;

  /// An extra that may charge twice for one thing.
  String xAlreadyOne(String what);

  /// An extra that may charge twice for some things.
  String xAlreadyMany(String what);

  /// A group already priced and what it comes to.
  String xAlreadyItem(String what, String amount);

  /// A percentage line: so much per cent of an amount.
  String ppPercentOf(String percent, String amount);

  /// A fixed price line.
  String get ppFixed;

  /// Rate check.
  String get ccEnterFigure;

  /// Rate check.
  String get ccRateNotBelow;

  /// Colour check.
  String get ccNameRequired;

  /// Colour check.
  String get ccChooseMaterial;

  /// Colour check.
  String ccNoProfile(String material);

  /// Colour check.
  String ccRateRequired(String material);

  /// Colour check.
  String ccNameTaken(String name, String material);

  /// Colour check.
  String get ccNotInList;

  /// Factory price check.
  String get rfNeeded;

  /// Factory price check.
  String get rfZeroOrMore;

  /// Factory price check.
  String get rfWhole;

  /// Price list section.
  String get rfGlassSingle;

  /// Price list section.
  String get rfSealed;

  /// Price list section.
  String get rfPanel;

  /// Price list field: a colour not named.
  String get rfAnyOtherColour;

  /// Price list section.
  String get rfHardware;

  /// Price list section.
  String get rfSliding;

  /// Price list field: a sliding track.
  String get rfTrack;

  /// Price list field.
  String get rfRoller;

  /// Price list field.
  String get rfRollersPerPanel;

  /// Price list section.
  String get rfInstallation;

  /// Price list field: a fixed figure a design.
  String get rfEachDesign;

  /// Price list field: a figure a square metre.
  String get rfByArea;

  /// Price list section.
  String get rfBorderLines;

  /// Price list section.
  String get rfOpeningProfile;

  /// Price list section.
  String rfAnyOtherColourOf(String material);

  /// Price list field.
  String get rfAMetre;

  /// Price list field.
  String get rfOnProfile;

  /// Price list section.
  String rfLabourOf(String category);

  /// Price list field.
  String get rfOnMaterials;

  /// Unit after a price field.
  String get rfUnitEach;

  /// Unit after a price field.
  String get rfUnitFixed;

  /// Unit after a price field.
  String get rfUnitRollers;

  /// A design's own discount check.
  String get discountDesignNotFinal;

  /// Name of a row of figures on the technical drawing: the overall size.
  String get dimOverall;

  /// Name of a row of figures: the main divisions' clear openings.
  String get dimDaylight;

  /// Name of a row of figures: each opening's size.
  String get dimOpening;

  /// Name of a row of figures: the divisions inside a part.
  String get dimDivision;

  /// Name of a row of figures: a side of an angled frame.
  String get dimSide;

  /// A figure being typed over.
  String get dimOverallWidth;

  /// A figure being typed over.
  String get dimOverallHeight;

  /// A figure being typed over: the width of a kind of part.
  String dimKindWidth(String what);

  /// A figure being typed over: the height of a kind of part.
  String dimKindHeight(String what);

  /// A figure being typed over.
  String get dimSectionWidth;

  /// A figure being typed over.
  String get dimSectionHeight;

  /// A drawn dimension being typed over.
  String get dimRealSize;

  /// Written on a pane of glass on the technical drawing.
  String get cadGlass;

  /// Written on a pane of tinted or frosted glass.
  String cadLookGlass(String look);

  /// Written by a leaf that opens inward.
  String get cadIn;

  /// Written by a leaf that opens outward.
  String get cadOut;

  /// Size check.
  String get msTooWide;

  /// Size check.
  String get msBarThickness;

  /// Size check.
  String get msSmallerThanFrame;

  /// Size check.
  String get msNotFitInside;

  /// Size check.
  String get msNotFitBeside;

  /// Size check.
  String get msNothing;

  /// Size check.
  String get msNotFit;

  /// Size check.
  String get msNoFrame;

  /// Price list upgrade note.
  String mnAluminium(String rate);

  /// Price list upgrade note.
  String mnBarRate(String material, String bar, String frame);

  /// Price list upgrade note.
  String mnLeaf(String each);

  /// Price list upgrade note.
  String mnJoint(String joint);

  /// Price list upgrade note.
  String get mnSealed;

  /// Price list upgrade note.
  String get mnCatalog;

}

/// The domain in English.
class EnglishWords implements Words {
  const EnglishWords();

  @override
  String get kindDoor =>
      'Door';

  @override
  String get kindWindow =>
      'Window';

  @override
  String get kindBoth =>
      'Door & window';

  @override
  String get kindSliding =>
      'Sliding';

  @override
  String get kindAngled =>
      'Angled / Asymmetrical';

  @override
  String get kindUnsupported =>
      'Unsupported category';

  @override
  String get nounDoor =>
      'door';

  @override
  String get nounWindow =>
      'window';

  @override
  String get nounBoth =>
      'door & window';

  @override
  String get nounSliding =>
      'sliding';

  @override
  String get nounAngled =>
      'angled design';

  @override
  String get nounUnsupported =>
      'design of an unsupported category';

  @override
  String untitledDesign(String noun) =>
      'Untitled $noun';

  @override
  String get constructionPending =>
      'Not said';

  @override
  String get constructionPanel =>
      'Panel';

  @override
  String get constructionGlass =>
      'Glass';

  @override
  String get constructionBoth =>
      'Panel + glass';

  @override
  String get matUpvc =>
      'uPVC';

  @override
  String get matAluminium =>
      'Aluminium';

  @override
  String get matWood =>
      'Wood';

  @override
  String get matSteel =>
      'Steel';

  @override
  String get matClearGlass =>
      'Clear glass';

  @override
  String get matFrostedGlass =>
      'Frosted glass';

  @override
  String get matTintedGlass =>
      'Tinted glass';

  @override
  String get matPanel =>
      'Solid panel';

  @override
  String get matLouvre =>
      'Louvre';

  @override
  String get matMesh =>
      'Insect mesh';

  @override
  String get matRubber =>
      'Rubber gasket';

  @override
  String get classGlass =>
      'Glass';

  @override
  String get classPanel =>
      'Panel';

  @override
  String get classPvc =>
      'PVC';

  @override
  String get classAluminium =>
      'Aluminium';

  @override
  String get classWood =>
      'Wood';

  @override
  String get classRubber =>
      'Rubber gasket';

  @override
  String get classMetal =>
      'Metal';

  @override
  String get classHandleMetal =>
      'Handle metal';

  @override
  String get classHingeMetal =>
      'Hinge metal';

  @override
  String get classMesh =>
      'Mesh';

  @override
  String get colourBlack =>
      'Black';

  @override
  String get colourWhite =>
      'White';

  @override
  String get colourSilver =>
      'Silver';

  @override
  String get colourGrey =>
      'Grey';

  @override
  String get colourBronze =>
      'Bronze';

  @override
  String get colourBrown =>
      'Brown';

  @override
  String get colourOffWhite =>
      'Off white';

  @override
  String get colourCream =>
      'Cream';

  @override
  String get colourGraphite =>
      'Graphite';

  @override
  String get colourDeepGreen =>
      'Deep green';

  @override
  String get colourSteelBlue =>
      'Steel blue';

  @override
  String get colourOak =>
      'Oak';

  @override
  String get colourWalnut =>
      'Walnut';

  @override
  String get colourOxblood =>
      'Oxblood';

  @override
  String get colourClearGlass =>
      'Clear glass';

  @override
  String get colourFrosted =>
      'Frosted';

  @override
  String get colourWarmCream =>
      'Warm cream';

  @override
  String get glassClear =>
      'Clear';

  @override
  String get glassTinted =>
      'Tinted';

  @override
  String get glassFrosted =>
      'Frosted';

  @override
  String get glassDark =>
      'Dark';

  @override
  String get glassBlueGrey =>
      'Blue-grey';

  @override
  String get mechFixed =>
      'Fixed';

  @override
  String get mechFixedHint =>
      'Does not open';

  @override
  String get mechHingedLeft =>
      'Hinged left';

  @override
  String get mechHingedLeftHint =>
      'Hinges on the left, opens from the right';

  @override
  String get mechHingedRight =>
      'Hinged right';

  @override
  String get mechHingedRightHint =>
      'Hinges on the right, opens from the left';

  @override
  String get mechTopHung =>
      'Top hung';

  @override
  String get mechTopHungHint =>
      'Hinges at the top, opens outward at the bottom';

  @override
  String get mechBottomHung =>
      'Bottom hung';

  @override
  String get mechBottomHungHint =>
      'Hinges at the bottom, opens inward at the top';

  @override
  String get mechSlidingLeft =>
      'Sliding left';

  @override
  String get mechSlidingLeftHint =>
      'Slides to the left';

  @override
  String get mechSlidingRight =>
      'Sliding right';

  @override
  String get mechSlidingRightHint =>
      'Slides to the right';

  @override
  String get mechTiltAndTurn =>
      'Tilt and turn';

  @override
  String get mechTiltAndTurnHint =>
      'Tilts at the top and turns on one side';

  @override
  String get mechBifold =>
      'Bi-fold';

  @override
  String get mechBifoldHint =>
      'Folds back in leaves';

  @override
  String get mechPivot =>
      'Pivot';

  @override
  String get mechPivotHint =>
      'Turns about a central axis';

  @override
  String get hwHandle =>
      'Handle';

  @override
  String get hwLever =>
      'Lever';

  @override
  String get hwKnob =>
      'Knob';

  @override
  String get hwLock =>
      'Lock';

  @override
  String get hwHinge =>
      'Hinge';

  @override
  String get hwLetterplate =>
      'Letter plate';

  @override
  String get hwPeephole =>
      'Peephole';

  @override
  String get hwCloser =>
      'Closer';

  @override
  String get hwPull =>
      'Pull handle';

  @override
  String get hwScreen =>
      'Pleated screen';

  @override
  String get hwSensor =>
      'Sensor';

  @override
  String get elFrame =>
      'Frame';

  @override
  String get elSection =>
      'Section';

  @override
  String get elNote =>
      'Note';

  @override
  String get elArrow =>
      'Arrow';

  @override
  String get elVerticalDivider =>
      'Vertical divider';

  @override
  String get elHorizontalDivider =>
      'Horizontal divider';

  @override
  String get elAngledDivider =>
      'Angled divider';

  @override
  String get payTypePayment =>
      'Payment';

  @override
  String get payTypeRefund =>
      'Refund';

  @override
  String get payCash =>
      'Cash';

  @override
  String get payBankTransfer =>
      'Bank transfer';

  @override
  String get payCard =>
      'Card';

  @override
  String get payOther =>
      'Other';

  @override
  String get payLegacy =>
      'Legacy / unknown';

  @override
  String payOtherDetail(String detail) =>
      'Other — $detail';

  @override
  String get discountPercent =>
      'Percentage';

  @override
  String get discountFixed =>
      'Fixed amount';

  @override
  String get projectionPerspective =>
      'Perspective';

  @override
  String get projectionParallel =>
      'Orthographic';

  @override
  String get groupNormalProfile =>
      'Border and internal lines';

  @override
  String get groupOpeningProfile =>
      'Opening profile';

  @override
  String get groupOtherProfile =>
      'Other profile';

  @override
  String get groupColour =>
      'Colour';

  @override
  String get groupGlass =>
      'Glass';

  @override
  String get groupPanel =>
      'Panel';

  @override
  String get groupHardware =>
      'Hardware';

  @override
  String get groupLabour =>
      'Labour';

  @override
  String get groupInstallation =>
      'Installation';

  @override
  String get unitEach =>
      'each';

  @override
  String get glassNotIncluded =>
      'Not included';

  @override
  String get glassNothingToCharge =>
      'No measurable glass to price';

  @override
  String get glassNotUsed =>
      'Not used';

  @override
  String get catSystemAluminium =>
      'System Aluminium';

  @override
  String get catBendShoulderAluminium =>
      'Bend Shoulder Aluminium';

  @override
  String get partBorder =>
      'Border';

  @override
  String get partLines =>
      'Internal lines';

  @override
  String openingNumbered(int number) =>
      'Opening $number';

  @override
  String get openingAlone =>
      'Opening';

  @override
  String get openingThe =>
      'the opening';

  @override
  String get partA =>
      'a part';

  @override
  String get placeHead =>
      'Head';

  @override
  String get placeSill =>
      'Sill';

  @override
  String get placeLeftJamb =>
      'Left jamb';

  @override
  String get placeRightJamb =>
      'Right jamb';

  @override
  String get placeRakingUpperLeft =>
      'Raking upper left side';

  @override
  String get placeRakingUpperRight =>
      'Raking upper right side';

  @override
  String get placeRakingLowerLeft =>
      'Raking lower left side';

  @override
  String get placeRakingLowerRight =>
      'Raking lower right side';

  @override
  String lineNumbered(int n) =>
      'Line $n';

  @override
  String lineInside(int n, String opening) =>
      'Line $n (inside $opening)';

  @override
  String get measFrameBorder =>
      'Frame border';

  @override
  String get measBarThickness =>
      'Bar thickness';

  @override
  String get measOverallWidth =>
      'Overall width';

  @override
  String get measOverallHeight =>
      'Overall height';

  @override
  String get axisWidth =>
      'Width';

  @override
  String get axisHeight =>
      'Height';

  @override
  String measFixedLight(int n) =>
      'Fixed light $n';

  @override
  String measPane(String around, String material, int n) =>
      '$around — $material $n';

  @override
  String sideHeight(String side) =>
      '$side height';

  @override
  String sideWidth(String side) =>
      '$side width';

  @override
  String joinAnd(String a, String b) =>
      '$a and $b';

  @override
  String joinOr(String a, String b) =>
      '$a or $b';

  @override
  String get reqUnsupported =>
      'This design\'s category is not supported by this version of ProFrame, so its price is unavailable.';

  @override
  String get reqNotRead =>
      'The drawing has changes that have not been read. Please Read the drawing before calculating the price.';

  @override
  String get reqFrame =>
      'Please complete the outer frame to calculate the price.';

  @override
  String get reqDraw =>
      'Please draw the design to calculate the price.';

  @override
  String reqGeometry(String problem) =>
      'Please correct the geometry to calculate the price: $problem';

  @override
  String get reqConstruction =>
      'Please choose what the door is built of — panel, glass or both — to calculate the price.';

  @override
  String get reqPanelOrGlass =>
      'Please complete the panel/glass selection to calculate the price.';

  @override
  String reqOpeningKind(String opening) =>
      'Please say whether $opening is a door or a window to calculate the price.';

  @override
  String reqFrameSizes(String which) =>
      'Please give the $which to calculate the price.';

  @override
  String reqGroupSizes(String group, String which) =>
      'Please complete the dimensions of $group (its $which) to calculate the price.';

  @override
  String get reqProfile =>
      'Please choose the material and colour of the profile to calculate the price.';

  @override
  String reqCategoryAll(String material, String choices) =>
      'Please choose whether the $material profile is $choices to calculate the price.';

  @override
  String reqCategorySome(String choices, String parts) =>
      'Please choose $choices for $parts to calculate the price.';

  @override
  String readinessMoreOne(String first, int more) =>
      '$first $more more thing needs completing too.';

  @override
  String readinessMoreMany(String first, int more) =>
      '$first $more more things need completing too.';

  @override
  String get takeoffNothing =>
      'Nothing has been drawn yet.';

  @override
  String get takeoffOutline =>
      'The outline cannot be measured.';

  @override
  String get takeoffNoSize =>
      'The design has no width or no height.';

  @override
  String colourNotForMaterial(String material) =>
      'Please select a colour available for $material.';

  @override
  String colourNotConfigured(String material) =>
      'Colour pricing is not configured for $material.';

  @override
  String get colourUnavailable =>
      'Colour pricing unavailable — please select an active colour.';

  @override
  String colourNoProfile(String material) =>
      'The price list has no price for $material profile.';

  @override
  String get gradeStandard =>
      'Standard colour';

  @override
  String get gradeNonStandard =>
      'Non-standard colour';

  @override
  String get gradeSpecial =>
      'Special colour';

  @override
  String get engineUnsupported =>
      'This version of ProFrame cannot price a design of this category.';

  @override
  String engineNoCategory(String kind) =>
      'The price list has no prices for $kind designs.';

  @override
  String engineMissing(String what) =>
      'The price list has no price for $what.';

  @override
  String engineExtraCurrency(String name, String currency, String listCurrency) =>
      'The extra charge "$name" is in $currency, and this design is priced in $listCurrency. Write it in $listCurrency.';

  @override
  String missProfile(String material) =>
      '$material profile';

  @override
  String missBorderLines(String what) =>
      '$what border and lines';

  @override
  String missInfill(String material) =>
      '$material infill';

  @override
  String missPiece(String piece) =>
      'a $piece';

  @override
  String get custom =>
      'Custom';

  @override
  String get notSelected =>
      'Not selected';

  @override
  String lineProfile(String what, String part) =>
      '$what — $part';

  @override
  String lineOpeningProfile(String material) =>
      'Opening profile — $material';

  @override
  String lineColour(String colour, String material, String grade) =>
      '$colour $material ($grade)';

  @override
  String get lineTrack =>
      'Sliding track';

  @override
  String lineGlass(String look) =>
      '$look glass';

  @override
  String lineSealed(String glass) =>
      'Sealed unit — $glass';

  @override
  String linePanel(String colour) =>
      '$colour panel';

  @override
  String linePieces(String piece) =>
      '${piece}s';

  @override
  String get lineRollers =>
      'Rollers';

  @override
  String get lineMaking =>
      'Making';

  @override
  String get lineMakingArea =>
      'Making, by area';

  @override
  String get lineMakingMaterials =>
      'Making, on materials';

  @override
  String get lineInstallation =>
      'Installation';

  @override
  String get lineInstallationArea =>
      'Installation, by area';

  @override
  String get stateNotRead =>
      'Drawing not read';

  @override
  String get stateComplete =>
      'Complete';

  @override
  String get stateIncomplete =>
      'Incomplete';

  @override
  String get noteNotRead =>
      'Price unavailable until drawing is read';

  @override
  String get noteNotCalculated =>
      'Not calculated yet';

  @override
  String get noteRecalculate =>
      'Price needs recalculation';

  @override
  String get noteIncomplete =>
      'Price unavailable until design is completed';

  @override
  String get noteUnavailable =>
      'Price unavailable';

  @override
  String get msgRecalculate =>
      'The design or the prices changed since this price was calculated. Calculate it again.';

  @override
  String get msgCalculate =>
      'Calculate the price.';

  @override
  String get reasonUnsupported =>
      'Unsupported category. Price unavailable.';

  @override
  String get reasonListCannot =>
      'The price list cannot price this design.';

  @override
  String get gfPartOfDesign =>
      'part of the design';

  @override
  String get gfFrame =>
      'the frame';

  @override
  String gfMemberOfFrame(String member) =>
      'the $member of the frame';

  @override
  String gfLineInside(String parent) =>
      'a line inside $parent';

  @override
  String get gfBar =>
      'a bar';

  @override
  String get gfMullion =>
      'a mullion';

  @override
  String get gfTransom =>
      'a transom';

  @override
  String get gfSlopedBar =>
      'a sloped bar';

  @override
  String gfPaneOf(String parent) =>
      'a pane of $parent';

  @override
  String gfRegionOf(String opening) =>
      'the region of $opening';

  @override
  String get gfFixedLight =>
      'a fixed light';

  @override
  String gfPieceOf(String piece, String opening) =>
      'a $piece of $opening';

  @override
  String gfPiece(String piece) =>
      'a $piece';

  @override
  String gfDimensionGiven(String size) =>
      'the dimension you gave as $size';

  @override
  String get gfDimension =>
      'a dimension';

  @override
  String get gfNote =>
      'a note';

  @override
  String get gfArrow =>
      'an arrow';

  @override
  String get gfLightItBelongsTo =>
      'the light it belongs to';

  @override
  String get gfPartItBelongsTo =>
      'the part it belongs to';

  @override
  String gfNotANumber(String name) =>
      '$name has a point that is not a number, so it cannot be placed.';

  @override
  String get gfFrameEnclosesNothing =>
      'The frame\'s outline does not enclose a shape.';

  @override
  String gfEnclosesNothing(String name) =>
      '$name encloses no area.';

  @override
  String get gfSidesCross =>
      'Two sides of the frame cross each other.';

  @override
  String gfSideCrosses(String first, String second) =>
      'The $first of the frame crosses the $second.';

  @override
  String get gfFrameTouchesItself =>
      'The frame\'s outline touches itself.';

  @override
  String gfCrossesItself(String name) =>
      '$name crosses itself.';

  @override
  String gfNotConnected(String name) =>
      '$name is not connected to the frame or to another bar.';

  @override
  String gfOutsideFrame(String name) =>
      '$name lies outside the frame.';

  @override
  String gfNotOnLeaf(String name) =>
      '$name is not on its leaf.';

  @override
  String gfLiesOutside(String name, String within) =>
      '$name lies outside $within.';

  @override
  String gfReachesOutside(String name, String within) =>
      '$name reaches outside $within.';

  @override
  String gfLostRegion(String name) =>
      '$name has lost the region it opens.';

  @override
  String gfMarkOutside(String name) =>
      'The mark of $name is outside the region it opens.';

  @override
  String get gfDimensionNothing =>
      'A dimension measures nothing: its two ends are at the same point.';

  @override
  String gfDimensionNotSize(String size) =>
      'A dimension gives $size, which is not a size.';

  @override
  String gfDimensionDisagrees(String stated, String measured) =>
      'The dimension you gave as $stated no longer matches the drawing, which measures $measured.';

  @override
  String get gfDimensionMismatch =>
      'A dimension does not match the drawing.';

  @override
  String get gfTitleAttention =>
      'Geometry needs attention';

  @override
  String get gfTitleReview =>
      'Geometry may need review';

  @override
  String get gfSummaryError =>
      'Part of this design cannot be built as it is drawn. Nothing has been changed for you — put it right on your drawing.';

  @override
  String get gfSummaryWarning =>
      'This design can be built, but something in it may not be what you meant. Nothing has been changed for you.';

  @override
  String get whyIncompleteOne =>
      '1 design is incomplete';

  @override
  String whyIncompleteMany(int n) =>
      '$n designs are incomplete';

  @override
  String get whyCannotOne =>
      '1 design cannot be priced';

  @override
  String whyCannotMany(int n) =>
      '$n designs cannot be priced';

  @override
  String get whyCalculateOne =>
      '1 design needs its price calculated';

  @override
  String whyCalculateMany(int n) =>
      '$n designs need their prices calculated';

  @override
  String get listComma =>
      ', ';

  @override
  String get sentenceStop =>
      '.';

  @override
  String whyExtraOne(String currencies, String currency) =>
      'An extra charge is in $currencies, not $currency.';

  @override
  String whyExtraMany(int n, String currencies, String currency) =>
      '$n extra charges are in $currencies, not $currency.';

  @override
  String get payNothingToPay =>
      'Nothing to pay';

  @override
  String get payPricingIncomplete =>
      'Pricing incomplete';

  @override
  String get payOutstanding =>
      'Outstanding';

  @override
  String get payPaidInFull =>
      'Paid in full';

  @override
  String get payCredit =>
      'Credit';

  @override
  String get capGroupCustomers =>
      'Customers';

  @override
  String get capGroupDesigns =>
      'Designs';

  @override
  String get capGroupPricing =>
      'Pricing';

  @override
  String get capGroupFinances =>
      'Customer finances';

  @override
  String get capGroupDiscounts =>
      'Discounts';

  @override
  String get capGroupQuotations =>
      'Quotations';

  @override
  String get capGroupPayments =>
      'Payments';

  @override
  String get capGroupReceipts =>
      'Receipts';

  @override
  String get capGroupExtras =>
      'Extra charges';

  @override
  String get capGroupStaff =>
      'Staff';

  @override
  String get capView =>
      'View';

  @override
  String get capAdd =>
      'Add';

  @override
  String get capEdit =>
      'Edit';

  @override
  String get capDelete =>
      'Delete';

  @override
  String get capCreate =>
      'Create';

  @override
  String get capEditAndDraw =>
      'Edit and draw';

  @override
  String get capViewPrices =>
      'View prices';

  @override
  String get capEditFactoryPrices =>
      'Edit factory prices';

  @override
  String get capViewSummary =>
      'View summary';

  @override
  String get capApplyAndChange =>
      'Apply and change';

  @override
  String get capChangeStatus =>
      'Change status';

  @override
  String get capViewHistory =>
      'View history';

  @override
  String get capRecordPayments =>
      'Record payments';

  @override
  String get capRecordRefunds =>
      'Record refunds';

  @override
  String get capIssue =>
      'Issue';

  @override
  String get capRemove =>
      'Remove';

  @override
  String get capAddEditStaff =>
      'Add and edit staff';

  @override
  String get capChangePermissions =>
      'Change permissions';

  @override
  String get roleOwner =>
      'Owner';

  @override
  String get roleStaff =>
      'Staff';

  @override
  String get roleNobody =>
      'Nobody signed in';

  @override
  String deniedPriceList(String who) =>
      'Only the owner can change the price list (asked by $who).';

  @override
  String deniedAction(String who, String action, String key) =>
      '$who does not have permission to $action ($key).';

  @override
  String get storeCustomerGone =>
      'This customer is no longer kept.';

  @override
  String get hasDesignOne =>
      '1 design';

  @override
  String hasDesignMany(int n) =>
      '$n designs';

  @override
  String get hasPaymentOne =>
      '1 payment';

  @override
  String hasPaymentMany(int n) =>
      '$n payments';

  @override
  String get hasReceiptOne =>
      '1 receipt';

  @override
  String hasReceiptMany(int n) =>
      '$n receipts';

  @override
  String get hasDiscount =>
      'a discount';

  @override
  String get hasQuotations =>
      'quotations';

  @override
  String get hasExtraOne =>
      '1 extra charge';

  @override
  String hasExtraMany(int n) =>
      '$n extra charges';

  @override
  String cannotDeleteCustomer(String name, String has) =>
      '$name cannot be deleted: they have $has. A customer is deleted only when nothing of theirs would go with them — delete each design on its own; payments, receipts, discounts and quotations are the workshop\'s records and are kept.';

  @override
  String get quotationGone =>
      'That quotation is not kept.';

  @override
  String get staffNameNeeded =>
      'Enter a name.';

  @override
  String get staffNameTaken =>
      'A member of staff is already called that.';

  @override
  String pinTooShort(int n) =>
      'Use at least $n digits.';

  @override
  String copyOf(String name) =>
      '$name (copy)';

  @override
  String get nameProblem =>
      'Enter a name for this design, such as the room or the place it is for.';

  @override
  String qSymbolPrompt(String glyph) =>
      'Which section does this $glyph belong to?';

  @override
  String get qSymbolDetail =>
      'The mark is outside the design, so there is no section it could be in. Say which one you meant.';

  @override
  String qSymbolOpen(String meaning) =>
      'Open this one, $meaning.';

  @override
  String get qNotASymbol =>
      'It is not an opening mark';

  @override
  String get qNotASymbolDetail =>
      'Build it as lines, exactly where it was drawn.';

  @override
  String get meanPointsLeft =>
      'hinged on the right, opening from the left';

  @override
  String get meanPointsRight =>
      'hinged on the left, opening from the right';

  @override
  String get meanPointsUp =>
      'hinged at the bottom, opening at the top';

  @override
  String get meanPointsDown =>
      'hinged at the top, opening at the bottom';

  @override
  String get whereUpper =>
      'upper';

  @override
  String get whereLower =>
      'lower';

  @override
  String get whereLeft =>
      'left';

  @override
  String get whereRight =>
      'right';

  @override
  String whereBoth(String vertical, String horizontal) =>
      '$vertical $horizontal';

  @override
  String sectionDescribed(String place, String size) =>
      'The $place section — $size';

  @override
  String get gapBottom =>
      'the bottom';

  @override
  String get gapTop =>
      'the top';

  @override
  String get gapLeft =>
      'the left side';

  @override
  String get gapRight =>
      'the right side';

  @override
  String get gapOne =>
      'one side';

  @override
  String qGapPrompt(String side) =>
      'Your design is not closed — $side is open.';

  @override
  String get qGapDetail =>
      'Do you want it this way, or are you going to change it? Nothing has been added or taken away.';

  @override
  String get qKeepOpen =>
      'Keep it open';

  @override
  String qKeepOpenDetail(String side) =>
      'Build it as drawn, with no frame across $side.';

  @override
  String qKeepOpenFootDetail(String side) =>
      'Build it as drawn, with no frame across $side — a door runs down to the floor.';

  @override
  String get qCloseIt =>
      'Close it';

  @override
  String qCloseItDetail(String side) =>
      'Put the frame across $side, straight between the two ends you drew.';

  @override
  String get qChangeIt =>
      'I will change it';

  @override
  String get qChangeItDetail =>
      'Go back to the drawing and draw it as you want it.';

  @override
  String get qNotClosedPrompt =>
      'The outline does not close. What would you like to do?';

  @override
  String get qNotClosedDetail =>
      'Your lines do not join up into a shape, so there is no outer frame yet. Nothing has been changed or added.';

  @override
  String get qDrawRest =>
      'Let me draw the rest';

  @override
  String get qDrawRestDetail =>
      'Go back to the drawing and close the outline yourself.';

  @override
  String qKindPrompt(String opening) =>
      'What is $opening?';

  @override
  String get qKindDetail =>
      'A mark says this section opens. It does not say whether it is a door or a window, and the two are not made the same. This is about this one opening; every other section is untouched.';

  @override
  String get qKindDoorDetail =>
      'A leaf you walk through.';

  @override
  String get qKindWindowDetail =>
      'A leaf you open from indoors.';

  @override
  String get qConstructionDoor =>
      'How should this door be constructed?';

  @override
  String get qConstructionDesign =>
      'How should this design be constructed?';

  @override
  String get qConstructionDetail =>
      'You decide what fills the parts you draw. Nothing is divided or moved for you, and every part can be changed later.';

  @override
  String get qOnePart =>
      'Your design has no internal division yet';

  @override
  String get qOnePartDetail =>
      'Draw a divider first to create separate panel and glass parts. Nothing is divided for you.';

  @override
  String get qParts =>
      'Which parts should be glass and which should be panel?';

  @override
  String get qPartsDetail =>
      'Choose for each part you drew. The lines stay exactly where you drew them.';

  @override
  String partNumbered(int number) =>
      'Part $number';

  @override
  String get partFixed =>
      'Fixed';

  @override
  String get payLegacyNote =>
      'Migrated from the previous customer payment balance.';

  @override
  String get amtEnter =>
      'Enter an amount.';

  @override
  String get amtMoreThanNothing =>
      'The amount must be more than nothing.';

  @override
  String get amtToTheCent =>
      'Enter the amount to the cent — two decimal places at most.';

  @override
  String get amtAsNumber =>
      'Enter the amount as a number, such as 500.00.';

  @override
  String get amtSmaller =>
      'Enter a smaller amount.';

  @override
  String get refundNothingPaid =>
      'Nothing has been paid, so nothing can be refunded.';

  @override
  String refundNothingPaidIn(String currency) =>
      'Nothing has been paid in $currency, so nothing can be refunded.';

  @override
  String refundTooMuch(String amount) =>
      'A refund cannot be more than the net paid, $amount.';

  @override
  String get paymentNotFuture =>
      'Payments cannot be dated in the future.';

  @override
  String get refundNotFuture =>
      'Refunds cannot be dated in the future.';

  @override
  String get rateAsNumber =>
      'Enter the rate as a number, such as 1.10.';

  @override
  String get rateMoreThanNothing =>
      'The rate must be more than nothing.';

  @override
  String get discountNone =>
      'No discount';

  @override
  String get discountEnter =>
      'Enter the discount.';

  @override
  String get discountMoreThanNothing =>
      'A discount must be more than nothing.';

  @override
  String get discountOver100 =>
      'A percentage cannot be more than 100%.';

  @override
  String get discountNotFinal =>
      'The total is not final yet. A fixed discount can be given once every design is priced.';

  @override
  String discountOverSubtotal(String amount) =>
      'The discount cannot be more than the subtotal, $amount.';

  @override
  String get discountPercentNumber =>
      'Enter the percentage as a number, such as 10 or 12.5.';

  @override
  String get qsDraft =>
      'Draft';

  @override
  String get qsIssued =>
      'Issued';

  @override
  String get qsAccepted =>
      'Accepted';

  @override
  String get qsRejected =>
      'Rejected';

  @override
  String get qsExpired =>
      'Expired';

  @override
  String get quoteIncomplete =>
      'Please complete all selected designs before creating the quotation.';

  @override
  String get quoteChooseOne =>
      'Choose at least one design.';

  @override
  String quoteNotReady(String message, String names) =>
      '$message Not ready: $names.';

  @override
  String quoteExtraCurrency(String name, String currency, String base) =>
      'The extra charge "$name" is in $currency, not $base. Write it in $base first.';

  @override
  String quoteDiscountExceeds(String discount, String subtotal) =>
      'The discount of $discount is more than this quotation\'s subtotal, $subtotal.';

  @override
  String quoteCannotBecome(String status, String next) =>
      'A quotation that is $status cannot become $next.';

  @override
  String get xcMaterial =>
      'Material';

  @override
  String get xcLabour =>
      'Labour';

  @override
  String get xcService =>
      'Service';

  @override
  String get xcTransport =>
      'Transport';

  @override
  String get xcInstallation =>
      'Installation';

  @override
  String get xcOther =>
      'Other';

  @override
  String get xuPiece =>
      'piece';

  @override
  String get xuPieces =>
      'pieces';

  @override
  String get xuBottle =>
      'bottle';

  @override
  String get xuBottles =>
      'bottles';

  @override
  String get xuHour =>
      'hour';

  @override
  String get xuHours =>
      'hours';

  @override
  String get xuMetre =>
      'metre';

  @override
  String get xuMetres =>
      'metres';

  @override
  String get xuSquareMetre =>
      'square metre';

  @override
  String get xuSquareMetres =>
      'square metres';

  @override
  String get xuKg =>
      'kg';

  @override
  String get xuKgs =>
      'kg';

  @override
  String get xuSet =>
      'set';

  @override
  String get xuSets =>
      'sets';

  @override
  String get xuRoll =>
      'roll';

  @override
  String get xuRolls =>
      'rolls';

  @override
  String get xuDay =>
      'day';

  @override
  String get xuDays =>
      'days';

  @override
  String get xuTrip =>
      'trip';

  @override
  String get xuTrips =>
      'trips';

  @override
  String get xNameNeeded =>
      'Enter what the extra is.';

  @override
  String get xQtyEnter =>
      'Enter the quantity.';

  @override
  String get xQtyMore =>
      'The quantity must be more than nothing.';

  @override
  String get xUnitNeeded =>
      'Choose or type the unit.';

  @override
  String get xPriceEnter =>
      'Enter the unit price.';

  @override
  String get xPriceNotBelow =>
      'A unit price cannot be below nothing.';

  @override
  String get xQtyNumber =>
      'Enter the quantity as a number, such as 5 or 2.5.';

  @override
  String get xQtyPlaces =>
      'Enter the quantity to three decimal places at most.';

  @override
  String get xPriceNumber =>
      'Enter the unit price as a number, such as 3.25.';

  @override
  String get xPricePlaces =>
      'Enter the unit price to the cent — two decimal places at most.';

  @override
  String xAlreadyOne(String what) =>
      '$what is already calculated from the design. Add this only if it is an additional charge.';

  @override
  String xAlreadyMany(String what) =>
      '$what are already calculated from the design. Add this only if it is an additional charge.';

  @override
  String xAlreadyItem(String what, String amount) =>
      '$what ($amount)';

  @override
  String ppPercentOf(String percent, String amount) =>
      '$percent% of $amount';

  @override
  String get ppFixed =>
      'fixed';

  @override
  String get ccEnterFigure =>
      'Enter a figure.';

  @override
  String get ccRateNotBelow =>
      'A rate cannot be below nothing.';

  @override
  String get ccNameRequired =>
      'Colour name is required.';

  @override
  String get ccChooseMaterial =>
      'Choose at least one material.';

  @override
  String ccNoProfile(String material) =>
      'The price list has no $material profile to sell a colour in.';

  @override
  String ccRateRequired(String material) =>
      '$material colour rate is required for a colour that applies to $material.';

  @override
  String ccNameTaken(String name, String material) =>
      'An active colour is already called $name for $material.';

  @override
  String get ccNotInList =>
      'This colour is not in the price list.';

  @override
  String get rfNeeded =>
      'A price is needed here.';

  @override
  String get rfZeroOrMore =>
      'Enter a figure of 0 or more.';

  @override
  String get rfWhole =>
      'Enter a whole number.';

  @override
  String get rfGlassSingle =>
      'Glass (single sheet)';

  @override
  String get rfSealed =>
      'Sealed glass unit';

  @override
  String get rfPanel =>
      'Panel';

  @override
  String get rfAnyOtherColour =>
      'Any other colour';

  @override
  String get rfHardware =>
      'Hardware';

  @override
  String get rfSliding =>
      'Sliding';

  @override
  String get rfTrack =>
      'Track';

  @override
  String get rfRoller =>
      'Roller';

  @override
  String get rfRollersPerPanel =>
      'Rollers on each sliding panel';

  @override
  String get rfInstallation =>
      'Installation';

  @override
  String get rfEachDesign =>
      'Each design';

  @override
  String get rfByArea =>
      'By area';

  @override
  String get rfBorderLines =>
      'Border and internal lines';

  @override
  String get rfOpeningProfile =>
      'Opening profile';

  @override
  String rfAnyOtherColourOf(String material) =>
      'Any other colour — $material';

  @override
  String get rfAMetre =>
      'A metre';

  @override
  String get rfOnProfile =>
      'On the profile';

  @override
  String rfLabourOf(String category) =>
      'Labour — $category';

  @override
  String get rfOnMaterials =>
      'On the materials';

  @override
  String get rfUnitEach =>
      'each';

  @override
  String get rfUnitFixed =>
      'fixed';

  @override
  String get rfUnitRollers =>
      'rollers';

  @override
  String get discountDesignNotFinal =>
      'The total is not final yet. A fixed discount can be given once it is priced.';

  @override
  String get dimOverall =>
      'Overall';

  @override
  String get dimDaylight =>
      'Daylight';

  @override
  String get dimOpening =>
      'Opening';

  @override
  String get dimDivision =>
      'Division';

  @override
  String get dimSide =>
      'Side';

  @override
  String get dimOverallWidth =>
      'Overall width';

  @override
  String get dimOverallHeight =>
      'Overall height';

  @override
  String dimKindWidth(String what) =>
      '$what width';

  @override
  String dimKindHeight(String what) =>
      '$what height';

  @override
  String get dimSectionWidth =>
      'Section width';

  @override
  String get dimSectionHeight =>
      'Section height';

  @override
  String get dimRealSize =>
      'Real size';

  @override
  String get cadGlass =>
      'GLASS';

  @override
  String cadLookGlass(String look) =>
      '$look GLASS';

  @override
  String get cadIn =>
      'IN';

  @override
  String get cadOut =>
      'OUT';

  @override
  String get msTooWide =>
      'Too wide for the frame.';

  @override
  String get msBarThickness =>
      'A bar has to have some thickness.';

  @override
  String get msSmallerThanFrame =>
      'Smaller than the frame around it.';

  @override
  String get msNotFitInside =>
      'That does not fit the parts inside it.';

  @override
  String get msNotFitBeside =>
      'That does not fit beside the parts next to it.';

  @override
  String get msNothing =>
      'Nothing to measure.';

  @override
  String get msNotFit =>
      'That does not fit.';

  @override
  String get msNoFrame =>
      'No frame.';

  @override
  String mnAluminium(String rate) =>
      'The aluminium border and lines rate ($rate a metre): aluminium is now priced as System Aluminium and Bend Shoulder Aluminium, each its own rate, and nothing says which of the two that rate was — so neither has a rate until one is set.';

  @override
  String mnBarRate(String material, String bar, String frame) =>
      'The $material bar rate ($bar a metre): bars are now normal profile, priced at the frame rate ($frame).';

  @override
  String mnLeaf(String each) =>
      'A price per leaf ($each): a leaf is now priced by its opening profile and its ironmongery.';

  @override
  String mnJoint(String joint) =>
      'A price per angled joint ($joint): an angled design is now priced by its own measurements.';

  @override
  String get mnSealed =>
      'Sealed glazing units are priced at the glass rates the list already had, which priced every pane before sealed units had a rate of their own.';

  @override
  String get mnCatalog =>
      'Colours are now one catalog: a colour sold in more than one material is one colour with a rate on each, at the figures it had.';

}
